modified.files.includes[relevant][analytics-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][analytics-java-rule]=\
    apps/analytics/**/*Test.java,\
    apps/content-dashboard/**/*Test.java,\
    apps/segments/**/*Test.java,\
    dxp/apps/analytics/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][analytics-java-rule]=\
    apps/analytics/**/*Test.java,\
    apps/content-dashboard/**/*Test.java,\
    apps/segments/**/*Test.java,\
    dxp/apps/analytics/**/*Test.java

relevant.rule.names=analytics-java-rule

test.batch.names[relevant][analytics-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
    (portal.acceptance == true) AND \
    (\
        (testray.component.names ~ "A/B Test") OR \
        (testray.component.names ~ "Personalization") OR \
        (testray.component.names ~ "Segmentation") OR \
        (testray.main.component.name ~ "A/B Test") OR \
        (testray.main.component.name ~ "Content Dashboard") OR \
        (testray.main.component.name ~ "Headless USM") OR \
        (testray.main.component.name ~ "Personalization") OR \
        (testray.main.component.name ~ "Segmentation")\
    )

testray.main.component.name=Analytics Cloud