modified.files.includes[relevant][oauth-client-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][oauth-client-java-rule]=\
    apps/oauth-client/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][oauth-client-java-rule]=\
    apps/oauth-client/**/*Test.java

relevant.rule.names=oauth-client-java-rule

test.batch.names[relevant][oauth-client-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
    (portal.acceptance == true) AND \
    (\
        (testray.component.names ~ "OAuth 2") OR \
        (testray.main.component.name ~ "OAuth 2")\
    )

testray.main.component.name=OAuth 2