#cloud-config

#
# The first line/comment is the shebang line for AWS cloud-init
#

disable_root: true
package_update: true
package_upgrade: true
runcmd:
    -   [groupadd, systemd-journal]
    -   [usermod, --append, --groups, systemd-journal, liferay]
    -   [usermod, --append, --groups, wheel, liferay]
    -   [mkdir, --parents, /opt/liferay/.ssh]
    -   [cp, /home/ec2-user/.ssh/authorized_keys, /opt/liferay/.ssh/authorized_keys]
    -   [chmod, 700, /opt/liferay/.ssh]
    -   [chmod, 600, /opt/liferay/.ssh/authorized_keys]
    -   [chown, --recursive, "liferay:liferay", /opt/liferay]
    -   [chmod, +x, /opt/liferay/bin/run_on_boot.sh]
    -   [su, --login, liferay, --command, /opt/liferay/bin/run_on_boot.sh]
    -   [gpasswd, --delete, ec2-user, wheel]
    -   [usermod, --lock, ec2-user]
users:
    -   default
    -   homedir: /opt/liferay
        name: liferay
        shell: /bin/bash
write_files:
    -   content: |
            export PS1='\[\e[31m\]\u@\h:\w\$ \[\e[0m\]'
            export KUBE_CONFIG_PATH="${HOME}/.kube/config"
        owner: liferay:liferay
        path: /opt/liferay/.bash_profile
        permissions: "0644"