modified.files.includes[relevant][portal-settings-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][portal-settings-java-rule]=\
    apps/portal-settings/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][portal-settings-java-rule]=\
    apps/portal-settings/**/*Test.java

relevant.rule.names=portal-settings-java-rule

test.batch.names[relevant][portal-settings-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
    (portal.acceptance == true) AND \
    (\
        (testray.component.names ~ "LDAP") OR \
        (testray.main.component.name ~ "LDAP") OR \
        (testray.main.component.name ~ "Login") OR \
        (testray.main.component.name ~ "OpenID Connect") OR \
        (testray.main.component.name ~ "Security")\
    )

testray.main.component.name=Login