#
# Application
#

liferay.marketplace.etc.spring.boot.url=${LIFERAY_MARKETPLACE_ETC_SPRING_BOOT_URL:http://localhost:58081}

#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay-marketplace-etc-cron-oahs.oauth2.headless.server.client.secret=${LIFERAY_MARKETPLACE_ETC_CRON_OAHS_CLIENT_SECRET}
liferay.oauth.application.external.reference.codes=liferay-marketplace-etc-cron-oahs