argocd_helm_chart_version="9.1.5"
argo_workflows_helm_chart_version="1.0.10"
crossplane_helm_chart_version="2.1.3"
envoy_gateway_helm_chart_version="1.6.3"
external_secrets_helm_chart_version="1.0.0"
infrastructure_helm_chart_version="0.0.10"
infrastructure_provider_helm_chart_version="0.2.0"
liferay_helm_chart_version="0.0.6"
