modified.files.includes[relevant][item-selector-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][item-selector-java-rule]=\
    apps/item-selector/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][item-selector-java-rule]=\
    apps/item-selector/**/*Test.java

relevant.rule.names=item-selector-java-rule

test.batch.names[relevant][item-selector-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
    (\
        (test.class.method.name == "BlogsPage#ViewRelatedAssetsInBlogs") OR \
        (test.class.method.name == "BlogsWidget#CanViewEntryWithOrganizationViaBlogsAggregator") OR \
        (test.class.method.name == "CollectionDisplay#ViewManualCollectionWithAssetTypes") OR \
        (test.class.method.name == "DMDocumentType#CanAddEntryWithMetadataSet") OR \
        (test.class.method.name == "DepotDocumentSiteIntegration#CanViewRelatedAssets") OR \
        (test.class.method.name == "SiteMemberships#AddMember") OR \
        (test.class.method.name == "WebContentDisplay#ChangeTemplate")\
    ) OR \
    (\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Item Selector") OR \
            (testray.main.component.name ~ "Item Selector")\
        )\
    )

testray.main.component.name=Item Selector