##
## Test Batch
##

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]=\
        (\
            (test.class.method.name == "BlogsPage#ViewRelatedAssetsInBlogs") OR \
            (test.class.method.name == "BlogsWidget#CanViewEntryWithOrganizationViaBlogsAggregator") OR \
            (test.class.method.name == "CollectionDisplay#ViewManualCollectionWithAssetTypes") OR \
            (test.class.method.name == "DMDocumentType#CanAddEntryWithMetadataSet") OR \
            (test.class.method.name == "DepotDocumentSiteIntegration#CanViewRelatedAssets") OR \
            (test.class.method.name == "SiteMemberships#AddMember") OR \
            (test.class.method.name == "WebContentDisplay#ChangeTemplate")\
        ) OR \
        (\
            (portal.acceptance == true) AND \
            (\
                (testray.component.names ~ "Item Selector") OR \
                (testray.main.component.name ~ "Item Selector")\
            )\
        )

##
## Testray
##

    testray.main.component.name=Item Selector