#
# This is a generated file.
#

api.version=v1.0
entity.class.name=com.liferay.headless.dsr.dto.v1_0.Room
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Headless.DSR)
osgi.jaxrs.resource=true