modified.files.includes[relevant][digital-sales-room-headless-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modified.files.includes[relevant][digital-sales-room-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modified.files.includes[relevant][digital-sales-room-playwright-rule]=**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][digital-sales-room-headless-rule]=\
    dxp/apps/digital-sales-room/headless/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][digital-sales-room-java-rule]=\
    dxp/apps/digital-sales-room/headless/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][digital-sales-room-headless-rule]=\
    dxp/apps/digital-sales-room/headless/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][digital-sales-room-java-rule]=\
    dxp/apps/digital-sales-room/headless/**/*Test.java

playwright.projects.includes[playwright-js-tomcat101-mysql84][relevant][digital-sales-room-playwright-rule]=\
    digital-sales-room-web.main

relevant.rule.names=\
    digital-sales-room-headless-rule,\
    digital-sales-room-java-rule,\
    digital-sales-room-playwright-rule

test.batch.names[relevant][digital-sales-room-headless-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.names[relevant][digital-sales-room-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.names[relevant][digital-sales-room-playwright-rule]=\
    playwright-js-tomcat101-mysql84

testray.main.component.name=Commerce