modified.files.includes[relevant][frontend-taglib-clay-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql84][relevant][frontend-taglib-clay-playwright-rule]=\
    frontend-taglib-clay.main

relevant.rule.names=frontend-taglib-clay-playwright-rule

test.batch.names[relevant][frontend-taglib-clay-playwright-rule]=\
    playwright-js-tomcat101-mysql84

test.batch.run.property.query[functional-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
    (testray.component.names == "Clay") OR \
    (\
        (\
            (test.class.method.name == "CommerceAccountSelector#CanCreateNewAccountInFlow") OR \
            (test.class.method.name == "KBPageTree#CanPageTreeExpandAndCollapseByClickingSameSectionIcon") OR \
            (test.class.method.name == "PagesTree#SearchAllPageTypes")\
        ) OR \
        (\
            (environment.acceptance == true) AND \
            (portal.acceptance == true) AND \
            (portal.upstream == true) AND \
            (\
                (app.server.types == null) OR \
                (app.server.types ~ "tomcat")\
            ) AND \
            (\
                (database.types == null) OR \
                (database.types ~ "mysql")\
            ) AND \
            (\
                (operating.system.types == null) OR \
                (operating.system.types ~ "centos")\
            )\
        )\
    )

ignoreParents[relevant][frontend-taglib-clay-rule]=true
testray.main.component.name=Frontend Taglib