#
# Application
#

liferay.seostudio.gsc.state.secret=${LIFERAY_SEOSTUDIO_GSC_STATE_SECRET}

#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay-seostudio-etc-gsc-oahs.oauth2.headless.server.client.secret=myfancypassword

liferay.oauth.application.external.reference.codes=\
    liferay-seostudio-etc-gsc-oahs,\
    liferay-seostudio-etc-gsc-oaua

liferay.oauth.urls.excludes=/callback,/info,/ready

#
# Spring Boot
#

server.forward-headers-strategy=FRAMEWORK
server.port=${PORT:58081}