modified.files.includes[relevant][data-cleanup-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modified.files.includes[relevant][data-cleanup-playwright-rule]=**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][data-cleanup-java-rule]=\
    apps/data-cleanup/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][data-cleanup-java-rule]=\
    apps/data-cleanup/**/*Test.java

playwright.projects.includes[playwright-js-tomcat101-postgresql163][relevant][data-cleanup-playwright-rule]=\
    data-cleanup.main

relevant.rule.names=\
    data-cleanup-java-rule,\
    data-cleanup-playwright-rule

test.batch.names[relevant][data-cleanup-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.names[relevant][data-cleanup-playwright-rule]=\
    playwright-js-tomcat101-postgresql163

testray.main.component.name=Data Cleanup