test.batch.run.property.query[functional-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
    (testray.main.component.name == "Database Partitioning")

testray.main.component.name=Database Partitioning