/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

module.exports = {
	build: {
		exports: [
			'html-to-image',
			'jspdf',
			'@liferay/js-api',
			'@liferay/js-api/data-set',
			'cropperjs/dist/cropper.css',
			'date-fns',
			'graphql-hooks-memcache',
			'graphql-hooks',
			'graphql',
			'highlight.js/styles/monokai-sublime.css',
			'qrcode',
			'react-dropzone',
			'react-transition-group',
			'uuid',
			'react-flow-renderer',
			'react-helmet',
			'react-router-dom',
			'graphiql',
			'graphiql/graphiql.css',
			{name: 'axe-core', symbols: 'auto'},
			{name: 'clipboard', symbols: 'auto'},
			{name: 'cropperjs', symbols: 'auto'},
			{name: 'dagre', symbols: 'auto'},
			{
				format: 'esm',
				name: 'dom-align',
				symbols: ['alignElement', 'alignPoint'],
			},
			{name: 'fuzzy', symbols: 'auto'},
			{name: 'highlight.js', symbols: 'auto'},
			{name: 'highlight.js/lib/core', symbols: 'auto'},
			{name: 'highlight.js/lib/languages/java', symbols: 'auto'},
			{name: 'highlight.js/lib/languages/javascript', symbols: 'auto'},
			{name: 'highlight.js/lib/languages/plaintext', symbols: 'auto'},
			{name: 'image-promise', symbols: 'auto'},
			{name: 'lodash.groupby', symbols: 'auto'},
			{name: 'lodash.isequal', symbols: 'auto'},
			{name: 'moment', symbols: 'auto'},
			{name: 'moment/min/moment-with-locales', symbols: 'auto'},
			{name: 'numeral', symbols: 'auto'},
			{name: 'object-hash', symbols: 'auto'},
			{name: 'qs', symbols: 'auto'},
			{name: 'react-text-mask', symbols: 'auto'},
			{name: 'text-mask-addons', symbols: 'auto'},
			{name: 'text-mask-core', symbols: 'auto'},
		],
	},
};
