/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.layout.content.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ExternalReferenceCodeModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LayoutContentVersion service. Represents a row in the &quot;LayoutContentVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.layout.content.model.impl.LayoutContentVersionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.layout.content.model.impl.LayoutContentVersionImpl</code>.
 * </p>
 *
 * @author Lourdes Fernández Besada
 * @see LayoutContentVersion
 * @generated
 */
@ProviderType
public interface LayoutContentVersionModel
	extends BaseModel<LayoutContentVersion>, ExternalReferenceCodeModel,
			GroupedModel, LocalizedModel, MVCCModel, ShardedModel,
			WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a layout content version model instance should use the {@link LayoutContentVersion} interface instead.
	 */

	/**
	 * Returns the primary key of this layout content version.
	 *
	 * @return the primary key of this layout content version
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this layout content version.
	 *
	 * @param primaryKey the primary key of this layout content version
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this layout content version.
	 *
	 * @return the mvcc version of this layout content version
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this layout content version.
	 *
	 * @param mvccVersion the mvcc version of this layout content version
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the external reference code of this layout content version.
	 *
	 * @return the external reference code of this layout content version
	 */
	@AutoEscape
	@Override
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this layout content version.
	 *
	 * @param externalReferenceCode the external reference code of this layout content version
	 */
	@Override
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the layout content version ID of this layout content version.
	 *
	 * @return the layout content version ID of this layout content version
	 */
	public long getLayoutContentVersionId();

	/**
	 * Sets the layout content version ID of this layout content version.
	 *
	 * @param layoutContentVersionId the layout content version ID of this layout content version
	 */
	public void setLayoutContentVersionId(long layoutContentVersionId);

	/**
	 * Returns the group ID of this layout content version.
	 *
	 * @return the group ID of this layout content version
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this layout content version.
	 *
	 * @param groupId the group ID of this layout content version
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this layout content version.
	 *
	 * @return the company ID of this layout content version
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this layout content version.
	 *
	 * @param companyId the company ID of this layout content version
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this layout content version.
	 *
	 * @return the user ID of this layout content version
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this layout content version.
	 *
	 * @param userId the user ID of this layout content version
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this layout content version.
	 *
	 * @return the user uuid of this layout content version
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this layout content version.
	 *
	 * @param userUuid the user uuid of this layout content version
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this layout content version.
	 *
	 * @return the user name of this layout content version
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this layout content version.
	 *
	 * @param userName the user name of this layout content version
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this layout content version.
	 *
	 * @return the create date of this layout content version
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this layout content version.
	 *
	 * @param createDate the create date of this layout content version
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this layout content version.
	 *
	 * @return the modified date of this layout content version
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this layout content version.
	 *
	 * @param modifiedDate the modified date of this layout content version
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the data of this layout content version.
	 *
	 * @return the data of this layout content version
	 */
	@AutoEscape
	public String getData();

	/**
	 * Sets the data of this layout content version.
	 *
	 * @param data the data of this layout content version
	 */
	public void setData(String data);

	/**
	 * Returns the data hash of this layout content version.
	 *
	 * @return the data hash of this layout content version
	 */
	@AutoEscape
	public String getDataHash();

	/**
	 * Sets the data hash of this layout content version.
	 *
	 * @param dataHash the data hash of this layout content version
	 */
	public void setDataHash(String dataHash);

	/**
	 * Returns the name of this layout content version.
	 *
	 * @return the name of this layout content version
	 */
	public String getName();

	/**
	 * Returns the localized name of this layout content version in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized name of this layout content version
	 */
	@AutoEscape
	public String getName(Locale locale);

	/**
	 * Returns the localized name of this layout content version in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this layout content version. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getName(Locale locale, boolean useDefault);

	/**
	 * Returns the localized name of this layout content version in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized name of this layout content version
	 */
	@AutoEscape
	public String getName(String languageId);

	/**
	 * Returns the localized name of this layout content version in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this layout content version
	 */
	@AutoEscape
	public String getName(String languageId, boolean useDefault);

	@AutoEscape
	public String getNameCurrentLanguageId();

	@AutoEscape
	public String getNameCurrentValue();

	/**
	 * Returns a map of the locales and localized names of this layout content version.
	 *
	 * @return the locales and localized names of this layout content version
	 */
	public Map<Locale, String> getNameMap();

	/**
	 * Sets the name of this layout content version.
	 *
	 * @param name the name of this layout content version
	 */
	public void setName(String name);

	/**
	 * Sets the localized name of this layout content version in the language.
	 *
	 * @param name the localized name of this layout content version
	 * @param locale the locale of the language
	 */
	public void setName(String name, Locale locale);

	/**
	 * Sets the localized name of this layout content version in the language, and sets the default locale.
	 *
	 * @param name the localized name of this layout content version
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setName(String name, Locale locale, Locale defaultLocale);

	public void setNameCurrentLanguageId(String languageId);

	/**
	 * Sets the localized names of this layout content version from the map of locales and localized names.
	 *
	 * @param nameMap the locales and localized names of this layout content version
	 */
	public void setNameMap(Map<Locale, String> nameMap);

	/**
	 * Sets the localized names of this layout content version from the map of locales and localized names, and sets the default locale.
	 *
	 * @param nameMap the locales and localized names of this layout content version
	 * @param defaultLocale the default locale
	 */
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale);

	/**
	 * Returns the plid of this layout content version.
	 *
	 * @return the plid of this layout content version
	 */
	public long getPlid();

	/**
	 * Sets the plid of this layout content version.
	 *
	 * @param plid the plid of this layout content version
	 */
	public void setPlid(long plid);

	/**
	 * Returns the spec schema version of this layout content version.
	 *
	 * @return the spec schema version of this layout content version
	 */
	@AutoEscape
	public String getSpecSchemaVersion();

	/**
	 * Sets the spec schema version of this layout content version.
	 *
	 * @param specSchemaVersion the spec schema version of this layout content version
	 */
	public void setSpecSchemaVersion(String specSchemaVersion);

	/**
	 * Returns the version of this layout content version.
	 *
	 * @return the version of this layout content version
	 */
	public int getVersion();

	/**
	 * Sets the version of this layout content version.
	 *
	 * @param version the version of this layout content version
	 */
	public void setVersion(int version);

	/**
	 * Returns the status of this layout content version.
	 *
	 * @return the status of this layout content version
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this layout content version.
	 *
	 * @param status the status of this layout content version
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this layout content version.
	 *
	 * @return the status by user ID of this layout content version
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this layout content version.
	 *
	 * @param statusByUserId the status by user ID of this layout content version
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this layout content version.
	 *
	 * @return the status by user uuid of this layout content version
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this layout content version.
	 *
	 * @param statusByUserUuid the status by user uuid of this layout content version
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this layout content version.
	 *
	 * @return the status by user name of this layout content version
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this layout content version.
	 *
	 * @param statusByUserName the status by user name of this layout content version
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this layout content version.
	 *
	 * @return the status date of this layout content version
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this layout content version.
	 *
	 * @param statusDate the status date of this layout content version
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this layout content version is approved.
	 *
	 * @return <code>true</code> if this layout content version is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this layout content version is denied.
	 *
	 * @return <code>true</code> if this layout content version is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this layout content version is a draft.
	 *
	 * @return <code>true</code> if this layout content version is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this layout content version is expired.
	 *
	 * @return <code>true</code> if this layout content version is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this layout content version is inactive.
	 *
	 * @return <code>true</code> if this layout content version is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this layout content version is incomplete.
	 *
	 * @return <code>true</code> if this layout content version is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this layout content version is pending.
	 *
	 * @return <code>true</code> if this layout content version is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this layout content version is scheduled.
	 *
	 * @return <code>true</code> if this layout content version is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public LayoutContentVersion cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:753649079