apiDir: ../headless-digital-sales-room-api/src/main/java
apiPackagePath: com.liferay.headless.digital.sales.room
application:
    baseURI: /headless-digital-sales-room
    className: HeadlessDigitalSalesRoomApplication
    name: Liferay.Headless.Digital.Sales.Room
author: Stefano Motta
clientDir: ../headless-digital-sales-room-client/src/main/java
compatibilityVersion: 13
forcePredictableOperationId: true
forcePredictableSchemaPropertyName: true
generateBatch: false
generateGraphQL: false
javaEEPackage: jakarta
testDir: ../headless-digital-sales-room-test/src/testIntegration/java