{{- if and .Values.backup.enabled .Values.backup.schedule -}}
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
    labels:
        component: backup-create-platform
    name: backup-create-scheduler-cron-workflow
    namespace: {{ .Release.Namespace }}
spec:
    concurrencyPolicy: Forbid
    schedules:
        -   {{ .Values.backup.schedule | quote }}
    startingDeadlineSeconds: 300
    workflowSpec:
        arguments:
            parameters:
                -   name: environment-id
                    value: {{ .Values.environmentId | quote }}
                -   name: project-id
                    value: {{ .Values.projectId | quote }}
        ttlStrategy:
            secondsAfterCompletion: 86400
        workflowTemplateRef:
            clusterScope: true
            name: backup-create-cluster-workflow-template
{{- end -}}