{{- if .Values.backup.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    labels:
        component: backup-cleanup-platform
        environmentId: {{ .Values.environmentId }}
        projectId: {{ .Values.projectId }}
    name: backup-cleanup-role
    namespace: {{ .Release.Namespace }}
rules:
    -   apiGroups: ["argoproj.io"]
        resources: ["workflowtaskresults"]
        verbs: ["create", "patch"]
    -   apiGroups: ["backup.liferay.cloud"]
        resources: ["liferaybackups"]
        verbs: ["delete", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    labels:
        component: backup-cleanup-platform
        environmentId: {{ .Values.environmentId }}
        projectId: {{ .Values.projectId }}
    name: backup-cleanup-rolebinding
    namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: backup-cleanup-role
subjects:
    -   kind: ServiceAccount
        name: {{ .Values.backup.cleanup.serviceAccountName }}
        namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
    labels:
        component: backup-cleanup-platform
        environmentId: {{ .Values.environmentId }}
        projectId: {{ .Values.projectId }}
    name: {{ .Values.backup.cleanup.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
{{- end -}}