{{- $templates := list -}}
{{- range $path, $_ := .Files.Glob "compositions/**" -}}
    {{- $content := $.Files.Get $path | trim -}}
    {{- if $content -}}
        {{- $templates = append $templates $content -}}
    {{- end -}}
{{- end -}}
{{- $templateHash := join "\n" (sortAlpha $templates) | sha256sum -}}
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-50"
        liferay.com/template-hash: {{ $templateHash | quote }}
    labels:
        liferay.com/template-hash: {{ printf "h-%s" $templateHash | trunc 63 | quote }}
    name: liferay-gcp-infrastructure-provider.gcp.liferay.com
spec:
    compositeTypeRef:
        apiVersion: gcp.liferay.com/v1alpha1
        kind: LiferayInfrastructure
    mode: Pipeline
    pipeline:
        -   functionRef:
                name: function-environment-configs
            input:
                apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
                kind: Input
                spec:
                    environmentConfigs:
                        -   ref:
                                name: environment-config
                            type: Reference
                        -   ref:
                                name: liferay-template-store
                            type: Reference
            step: environment-configs
        -   functionRef:
                name: function-go-templating
            input:
                apiVersion: gotemplating.fn.crossplane.io/v1beta1
                inline:
                    template: |
                        {{- .Files.Get "compositions/00-globals.gotmpl" | nindent 24 }}
                        {{- range $path, $_ := .Files.Glob "compositions/[1-9]*" }}
                        ---
                        {{ $.Files.Get $path | nindent 24 }}
                        {{- end }}
                kind: Input
                source: Inline
            step: go-templating
        -   functionRef:
                name: function-auto-ready
            step: auto-detect-ready-composed-resources