{{- if and .Values.gateway.enabled .Values.gateway.className .Values.gateway.namespace }}
{{- $gatewayProxyConfigName := "liferay-proxy-config" }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-110"
    labels:
        app: liferay
        component: gateway
    name: {{ $gatewayProxyConfigName }}
    namespace: {{ .Values.gateway.namespace }}
spec:
    provider:
        kubernetes:
            envoyDeployment:
                pod:
                    annotations:
                        iam.gke.io/gcp-service-account: {{ printf "%s-envoy-proxy@%s.iam.gserviceaccount.com" .Values.deploymentName .Values.global.gcp.projectId | quote }}
                    topologySpreadConstraints:
                        -   labelSelector:
                                matchLabels:
                                    app.kubernetes.io/name: envoy
                            maxSkew: 1
                            topologyKey: kubernetes.io/hostname
                            whenUnsatisfiable: ScheduleAnyway
                replicas: 3
            envoyHpa:
                maxReplicas: 10
                metrics:
                    -   resource:
                            name: cpu
                            target:
                                averageUtilization: 75
                                type: Utilization
                        type: Resource
                minReplicas: 3
            envoyService:
                annotations:
                    cloud.google.com/neg: "{\"ingress\": true}"
                    {{- if not .Values.gateway.internetFacing }}
                    networking.gke.io/internal-load-balancer-allow-global-access: "true"
                    networking.gke.io/load-balancer-type: Internal
                    {{- end }}
                externalTrafficPolicy: Local
                type: LoadBalancer
        type: Kubernetes
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-110"
    labels:
        app: liferay
        component: gateway
    name: {{ .Values.gateway.className }}
spec:
    controllerName: gateway.envoyproxy.io/gatewayclass-controller
    parametersRef:
        group: gateway.envoyproxy.io
        kind: EnvoyProxy
        name: {{ $gatewayProxyConfigName }}
        namespace: {{ .Values.gateway.namespace }}
{{- end -}}