modified.files.includes[relevant][frontend-js-aui-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat90-mysql84][relevant][frontend-js-aui-web-playwright-rule]=\
    frontend-js-aui-web.main

relevant.rule.names=frontend-js-aui-web-playwright-rule

test.batch.names[relevant][frontend-js-aui-web-playwright-rule]=\
    playwright-js-tomcat90-mysql84

test.batch.run.property.query[functional-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
    (\
        (portal.acceptance == true) AND \
        (portal.upstream == true)\
    ) AND \
    (\
        (app.server.types == null) OR \
        (app.server.types ~ "tomcat")\
    ) AND \
    (\
        (database.types == null) OR \
        (database.types ~ "mysql")\
    )

testray.main.component.name=Frontend JS