modified.files.includes[relevant][ai-hub-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][ai-hub-java-rule]=\
    dxp/apps/ai-hub/**/*Test.java

relevant.rule.names=ai-hub-java-rule
test.batch.names[relevant][ai-hub-java-rule]=modules-integration-postgresql163

testray.main.component.name=AI Hub