modified.files.includes[relevant][asset-functional-rule]=**

modified.files.includes[relevant][asset-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-*][relevant][asset-java-rule]=\
    apps/asset/**/*Test.java,\
    apps/document-library/**/src/testIntegration/**/*Test.java,\
    apps/fragment/**/src/testIntegration/**/*Test.java,\
    apps/segments/**/src/testIntegration/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][asset-java-rule]=\
    apps/asset/**/*Test.java,\
    apps/document-library/**/src/test/**/*Test.java,\
    apps/fragment/**/src/test/**/*Test.java,\
    apps/segments/**/*Test.java

relevant.rule.names=\
    asset-functional-rule,\
    asset-java-rule

test.batch.names[relevant][asset-functional-rule]=\
    functional-upgrade-tomcat90-mysql84

test.batch.names[relevant][asset-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
    (portal.acceptance == true) AND \
    (\
        (testray.component.names ~ "Auto Tagging") OR \
        (testray.component.names ~ "Categories") OR \
        (testray.component.names ~ "Collections") OR \
        (testray.component.names ~ "Document Management") OR \
        (testray.component.names ~ "Personalization") OR \
        (testray.component.names ~ "Segmentation") OR \
        (testray.main.component.name ~ "Asset Publisher Widget") OR \
        (testray.main.component.name ~ "Auto Tagging") OR \
        (testray.main.component.name ~ "Categories") OR \
        (testray.main.component.name ~ "Collections") OR \
        (testray.main.component.name ~ "Document Management") OR \
        (testray.main.component.name ~ "Headless USM") OR \
        (testray.main.component.name ~ "Localization") OR \
        (testray.main.component.name ~ "Message Boards") OR \
        (testray.main.component.name ~ "Personalization") OR \
        (testray.main.component.name ~ "Recycle Bin") OR \
        (testray.main.component.name ~ "Related Assets Widget") OR \
        (testray.main.component.name ~ "Segmentation") OR \
        (testray.main.component.name ~ "Tags")\
    )

test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][asset-functional-rule]=\
    (portal.acceptance == true) AND \
    (\
        (testray.component.names ~ "Documents and Media") AND \
        (testray.main.component.name ~ "Upgrades Collaboration")\
    )

testray.main.component.name=Asset Framework