/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.kernel.upgrade.recorder;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.dao.jdbc.util.ConnectionWrapper;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.security.auth.CompanyThreadLocal;
import com.liferay.portal.kernel.util.PropsValues;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.lang.reflect.InvocationHandler;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.util.Collections;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

/**
 * @author István András Dézsi
 */
public class UpgradeLogProgressTracker {

	public static Map<String, Long> getLastKnownProgresses() {
		return Collections.unmodifiableMap(_lastKnownProgresses);
	}

	public static void start() {
		_lastKnownProgresses.clear();

		if (!PropsValues.UPGRADE_LOG_PROGRESS_ENABLED) {
			return;
		}

		_enabled = true;

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Granular progress logging for upgrades is enabled. This may " +
					"decrease performance.");
		}
	}

	public static void stop() {
		_enabled = false;
	}

	public static Connection wrap(
		Connection connection, String upgradeProcessClassName) {

		if (!_enabled) {
			return connection;
		}

		return new ConnectionWrapper(connection) {

			@Override
			public Statement createStatement() throws SQLException {
				return _wrap(
					super.createStatement(), this, upgradeProcessClassName);
			}

			@Override
			public Statement createStatement(
					int resultSetType, int resultSetConcurrency)
				throws SQLException {

				return _wrap(
					super.createStatement(resultSetType, resultSetConcurrency),
					this, upgradeProcessClassName);
			}

			@Override
			public Statement createStatement(
					int resultSetType, int resultSetConcurrency,
					int resultSetHoldability)
				throws SQLException {

				return _wrap(
					super.createStatement(
						resultSetType, resultSetConcurrency,
						resultSetHoldability),
					this, upgradeProcessClassName);
			}

			@Override
			public CallableStatement prepareCall(String sql)
				throws SQLException {

				return (CallableStatement)_wrap(
					super.prepareCall(sql), this, upgradeProcessClassName);
			}

			@Override
			public CallableStatement prepareCall(
					String sql, int resultSetType, int resultSetConcurrency)
				throws SQLException {

				return (CallableStatement)_wrap(
					super.prepareCall(sql, resultSetType, resultSetConcurrency),
					this, upgradeProcessClassName);
			}

			@Override
			public CallableStatement prepareCall(
					String sql, int resultSetType, int resultSetConcurrency,
					int resultSetHoldability)
				throws SQLException {

				return (CallableStatement)_wrap(
					super.prepareCall(
						sql, resultSetType, resultSetConcurrency,
						resultSetHoldability),
					this, upgradeProcessClassName);
			}

			@Override
			public PreparedStatement prepareStatement(String sql)
				throws SQLException {

				return (PreparedStatement)_wrap(
					super.prepareStatement(sql), this, upgradeProcessClassName);
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, int autoGeneratedKeys)
				throws SQLException {

				return (PreparedStatement)_wrap(
					super.prepareStatement(sql, autoGeneratedKeys), this,
					upgradeProcessClassName);
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, int resultSetType, int resultSetConcurrency)
				throws SQLException {

				return (PreparedStatement)_wrap(
					super.prepareStatement(
						sql, resultSetType, resultSetConcurrency),
					this, upgradeProcessClassName);
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, int resultSetType, int resultSetConcurrency,
					int resultSetHoldability)
				throws SQLException {

				return (PreparedStatement)_wrap(
					super.prepareStatement(
						sql, resultSetType, resultSetConcurrency,
						resultSetHoldability),
					this, upgradeProcessClassName);
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, int[] columnIndexes)
				throws SQLException {

				return (PreparedStatement)_wrap(
					super.prepareStatement(sql, columnIndexes), this,
					upgradeProcessClassName);
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, String[] columnNames)
				throws SQLException {

				return (PreparedStatement)_wrap(
					super.prepareStatement(sql, columnNames), this,
					upgradeProcessClassName);
			}

		};
	}

	private static ResultSet _wrap(
		ResultSet resultSet, Statement statementProxy,
		String upgradeProcessClassName) {

		if (resultSet == null) {
			return null;
		}

		return (ResultSet)ProxyUtil.newProxyInstance(
			UpgradeLogProgressTracker.class.getClassLoader(),
			new Class<?>[] {ResultSet.class},
			new ResultSetInvocationHandler(
				resultSet, statementProxy, upgradeProcessClassName));
	}

	private static Statement _wrap(
		Statement statement, Connection wrapperConnection,
		String upgradeProcessClassName) {

		if (statement == null) {
			return null;
		}

		Class<?>[] classes = null;

		if (statement instanceof CallableStatement) {
			classes = new Class<?>[] {CallableStatement.class};
		}
		else if (statement instanceof PreparedStatement) {
			classes = new Class<?>[] {PreparedStatement.class};
		}
		else {
			classes = new Class<?>[] {Statement.class};
		}

		return (Statement)ProxyUtil.newProxyInstance(
			UpgradeLogProgressTracker.class.getClassLoader(), classes,
			new StatementInvocationHandler(
				statement, wrapperConnection, upgradeProcessClassName));
	}

	private static final Log _log = LogFactoryUtil.getLog(
		UpgradeLogProgressTracker.class);

	private static volatile boolean _enabled;
	private static final AtomicLong _handlerCounter = new AtomicLong();
	private static final Map<String, Long> _lastKnownProgresses =
		new ConcurrentHashMap<>();

	private static class ResultSetInvocationHandler
		implements InvocationHandler {

		@Override
		public Object invoke(Object proxy, Method method, Object[] args)
			throws Throwable {

			String methodName = method.getName();

			if (Objects.equals(methodName, "getStatement")) {
				return _statementProxy;
			}

			Object result = null;

			try {
				result = method.invoke(_resultSet, args);
			}
			catch (InvocationTargetException invocationTargetException) {
				throw invocationTargetException.getTargetException();
			}

			if (Objects.equals(methodName, "next") &&
				Objects.equals(result, Boolean.TRUE)) {

				_rowCount++;

				long now = System.currentTimeMillis();

				if ((now - _lastLogTime) >
						PropsValues.UPGRADE_LOG_PROGRESS_INTERVAL) {

					_lastKnownProgresses.put(_registryKey, _rowCount);

					if (_log.isInfoEnabled()) {
						_log.info(
							StringBundler.concat(
								_registryKey, " is still executing. Processed ",
								_rowCount, " rows."));
					}

					_lastLogTime = now;
				}
			}
			else if (Objects.equals(methodName, "close")) {
				if (_lastKnownProgresses.remove(_registryKey) != null) {
					if (_log.isInfoEnabled()) {
						_log.info(_registryKey + " finished.");
					}
				}
			}

			return result;
		}

		private ResultSetInvocationHandler(
			ResultSet resultSet, Statement statementProxy,
			String upgradeProcessClassName) {

			_resultSet = resultSet;
			_statementProxy = statementProxy;

			long handlerId = _handlerCounter.incrementAndGet();

			if (PropsValues.DATABASE_PARTITION_ENABLED) {
				_registryKey = StringBundler.concat(
					upgradeProcessClassName, " {companyId=",
					CompanyThreadLocal.getCompanyId(), ", handlerId=",
					handlerId, "}");
			}
			else {
				_registryKey = StringBundler.concat(
					upgradeProcessClassName, " {handlerId=", handlerId, "}");
			}

			_lastLogTime = System.currentTimeMillis();
		}

		private long _lastLogTime;
		private final String _registryKey;
		private final ResultSet _resultSet;
		private long _rowCount;
		private final Statement _statementProxy;

	}

	private static class StatementInvocationHandler
		implements InvocationHandler {

		@Override
		public Object invoke(Object proxy, Method method, Object[] args)
			throws Throwable {

			if (Objects.equals(method.getName(), "getConnection")) {
				return _wrapperConnection;
			}

			Object result = null;

			try {
				result = method.invoke(_statement, args);
			}
			catch (InvocationTargetException invocationTargetException) {
				throw invocationTargetException.getTargetException();
			}

			if (result instanceof ResultSet) {
				return _wrap(
					(ResultSet)result, (Statement)proxy,
					_upgradeProcessClassName);
			}

			return result;
		}

		private StatementInvocationHandler(
			Statement statement, Connection wrapperConnection,
			String upgradeProcessClassName) {

			_statement = statement;
			_wrapperConnection = wrapperConnection;
			_upgradeProcessClassName = upgradeProcessClassName;
		}

		private final Statement _statement;
		private final String _upgradeProcessClassName;
		private final Connection _wrapperConnection;

	}

}