modified.files.includes[relevant][digital-sales-room-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql84][relevant][digital-sales-room-web-playwright-rule]=\
    digital-sales-room-web.main

relevant.rule.names=digital-sales-room-web-playwright-rule

test.batch.names[relevant][digital-sales-room-web-playwright-rule]=\
    playwright-js-tomcat101-mysql84