/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.segments.model.impl;

import com.liferay.segments.model.SegmentsExperienceAudienceEntryRel;
import com.liferay.segments.service.SegmentsExperienceAudienceEntryRelLocalServiceUtil;

/**
 * The extended model base implementation for the SegmentsExperienceAudienceEntryRel service. Represents a row in the &quot;SExperienceAudienceEntryRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SegmentsExperienceAudienceEntryRelImpl}.
 * </p>
 *
 * @author Eduardo Garcia
 * @see SegmentsExperienceAudienceEntryRelImpl
 * @see SegmentsExperienceAudienceEntryRel
 * @generated
 */
public abstract class SegmentsExperienceAudienceEntryRelBaseImpl
	extends SegmentsExperienceAudienceEntryRelModelImpl
	implements SegmentsExperienceAudienceEntryRel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a segments experience audience entry rel model instance should use the <code>SegmentsExperienceAudienceEntryRel</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SegmentsExperienceAudienceEntryRelLocalServiceUtil.
				addSegmentsExperienceAudienceEntryRel(this);
		}
		else {
			SegmentsExperienceAudienceEntryRelLocalServiceUtil.
				updateSegmentsExperienceAudienceEntryRel(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-1216000391