/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

export const ADD_FRAGMENT_COMPOSITION = 'ADD_FRAGMENT_COMPOSITION';
export const ADD_FRAGMENT_ENTRY_LINKS = 'ADD_FRAGMENT_ENTRY_LINKS';
export const ADD_FRAGMENT_ENTRY_LINK_COMMENT =
	'ADD_FRAGMENT_ENTRY_LINK_COMMENT';
export const ADD_ITEM = 'ADD_ITEM';
export const ADD_MAPPED_INFO_ITEM = 'ADD_MAPPED_INFO_ITEM';
export const ADD_MAPPING_FIELDS = 'ADD_MAPPING_FIELDS';
export const ADD_REDO_ACTION = 'ADD_REDO_ACTION';
export const ADD_RULE = 'ADD_RULE';
export const ADD_STEPPER = 'ADD_STEPPER';
export const ADD_UNDO_ACTION = 'ADD_UNDO_ACTION';
export const CHANGE_MASTER_LAYOUT = 'CHANGE_MASTER_LAYOUT';
export const DELETE_FRAGMENT_ENTRY_LINK_COMMENT =
	'DELETE_FRAGMENT_ENTRY_LINK_COMMENT';
export const DELETE_ITEM = 'DELETE_ITEM';
export const DELETE_RULE = 'DELETE_RULE';
export const DUPLICATE_ITEM = 'DUPLICATE_ITEM';
export const EDIT_FRAGMENT_ENTRY_LINK_COMMENT =
	'EDIT_FRAGMENT_ENTRY_LINK_COMMENT';
export const INIT = 'INIT';
export const LOAD_REDUCER = 'LOAD_REDUCER';
export const MOVE_ITEM = 'MOVE_ITEM';
export const MOVE_STEPPER = 'MOVE_STEPPER';
export const PASTE_ITEM = 'PASTE_ITEM';
export const REMOVE_FORM_STEP = 'REMOVE_FORM_STEP';
export const SWAP_FRAGMENT = 'SWAP_FRAGMENT';
export const SWITCH_SIDEBAR_PANEL = 'SWITCH_SIDEBAR_PANEL';
export const SWITCH_VIEWPORT_SIZE = 'SWITCH_VIEWPORT_SIZE';
export const TOGGLE_FRAGMENT_HIGHLIGHTED = 'TOGGLE_FRAGMENT_HIGHLIGHTED';
export const TOGGLE_PERMISSION = 'TOGGLE_PERMISSION';
export const TOGGLE_SHOW_RESOLVED_COMMENTS = 'TOGGLE_SHOW_RESOLVED_COMMENTS';
export const TOGGLE_WIDGET_HIGHLIGHTED = 'TOGGLE_WIDGET_HIGHLIGHTED';
export const UNLOAD_REDUCER = 'UNLOAD_REDUCER';
export const UPDATE_COL_SIZE = 'UPDATE_COL_SIZE';
export const UPDATE_COLLECTION_DISPLAY_COLLECTION =
	'UPDATE_COLLECTION_DISPLAY_COLLECTION';
export const UPDATE_DRAFT = 'UPDATE_DRAFT';
export const UPDATE_EDITABLE_VALUES = 'UPDATE_EDITABLE_VALUES';
export const UPDATE_ITEM_CONFIG = 'UPDATE_ITEM_CONFIG';
export const UPDATE_FORM_ITEM_CONFIG = 'UPDATE_FORM_ITEM_CONFIG';
export const UPDATE_FRAGMENT_ENTRY_LINK_CONFIGURATION =
	'UPDATE_FRAGMENT_ENTRY_LINK_CONFIGURATION';
export const UPDATE_FRAGMENT_ENTRY_LINK_CONTENT =
	'UPDATE_FRAGMENT_ENTRY_LINK_CONTENT';
export const UPDATE_FRAGMENT_ENTRY_LINKS_CONTENT =
	'UPDATE_FRAGMENT_ENTRY_LINKS_CONTENT';
export const UPDATE_FRAGMENTS = 'UPDATE_FRAGMENTS';
export const UPDATE_LANGUAGE_ID = 'UPDATE_LANGUAGE_ID';
export const UPDATE_NETWORK = 'UPDATE_NETWORK';
export const UPDATE_REDO_ACTIONS = 'UPDATE_REDO_ACTIONS';
export const UPDATE_ROW_COLUMNS = 'UPDATE_ROW_COLUMNS';
export const UPDATE_UNDO_ACTIONS = 'UPDATE_UNDO_ACTIONS';
export const UPDATE_PREVIEW_IMAGE = 'UPDATE_PREVIEW_IMAGE';
export const UPDATE_RULE = 'UPDATE_RULE';
export const UPDATE_RULES = 'UPDATE_RULES';
export const UPDATE_WIDGETS = 'UPDATE_WIDGETS';
