modified.files.includes[relevant][click-to-chat-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][click-to-chat-java-rule]=\
    apps/click-to-chat/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][click-to-chat-java-rule]=\
    apps/click-to-chat/**/*Test.java

relevant.rule.names=click-to-chat-java-rule

test.batch.names[relevant][click-to-chat-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
    (portal.acceptance == true) AND \
    (\
        (testray.component.names ~ "Click to Chat") OR \
        (testray.main.component.name ~ "Click to Chat")\
    )

testray.main.component.name=Click to Chat