/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.model.DynamicQueryEntry;
import com.liferay.portal.tools.service.builder.test.service.DynamicQueryEntryLocalService;
import com.liferay.portal.tools.service.builder.test.service.DynamicQueryEntryLocalServiceUtil;
import com.liferay.portal.tools.service.builder.test.service.persistence.DynamicQueryEntryPersistence;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the dynamic query entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.DynamicQueryEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.DynamicQueryEntryLocalServiceImpl
 * @generated
 */
public abstract class DynamicQueryEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements DynamicQueryEntryLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>DynamicQueryEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>DynamicQueryEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the dynamic query entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DynamicQueryEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dynamicQueryEntry the dynamic query entry
	 * @return the dynamic query entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DynamicQueryEntry addDynamicQueryEntry(
		DynamicQueryEntry dynamicQueryEntry) {

		dynamicQueryEntry.setNew(true);

		return dynamicQueryEntryPersistence.update(dynamicQueryEntry);
	}

	/**
	 * Creates a new dynamic query entry with the primary key. Does not add the dynamic query entry to the database.
	 *
	 * @param dynamicQueryEntryId the primary key for the new dynamic query entry
	 * @return the new dynamic query entry
	 */
	@Override
	@Transactional(enabled = false)
	public DynamicQueryEntry createDynamicQueryEntry(long dynamicQueryEntryId) {
		return dynamicQueryEntryPersistence.create(dynamicQueryEntryId);
	}

	/**
	 * Deletes the dynamic query entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DynamicQueryEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dynamicQueryEntryId the primary key of the dynamic query entry
	 * @return the dynamic query entry that was removed
	 * @throws PortalException if a dynamic query entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DynamicQueryEntry deleteDynamicQueryEntry(long dynamicQueryEntryId)
		throws PortalException {

		return dynamicQueryEntryPersistence.remove(dynamicQueryEntryId);
	}

	/**
	 * Deletes the dynamic query entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DynamicQueryEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dynamicQueryEntry the dynamic query entry
	 * @return the dynamic query entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DynamicQueryEntry deleteDynamicQueryEntry(
		DynamicQueryEntry dynamicQueryEntry) {

		return dynamicQueryEntryPersistence.remove(dynamicQueryEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return dynamicQueryEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			DynamicQueryEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return dynamicQueryEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.DynamicQueryEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return dynamicQueryEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.DynamicQueryEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return dynamicQueryEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return dynamicQueryEntryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return dynamicQueryEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public DynamicQueryEntry fetchDynamicQueryEntry(long dynamicQueryEntryId) {
		return dynamicQueryEntryPersistence.fetchByPrimaryKey(
			dynamicQueryEntryId);
	}

	/**
	 * Returns the dynamic query entry with the primary key.
	 *
	 * @param dynamicQueryEntryId the primary key of the dynamic query entry
	 * @return the dynamic query entry
	 * @throws PortalException if a dynamic query entry with the primary key could not be found
	 */
	@Override
	public DynamicQueryEntry getDynamicQueryEntry(long dynamicQueryEntryId)
		throws PortalException {

		return dynamicQueryEntryPersistence.findByPrimaryKey(
			dynamicQueryEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			dynamicQueryEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DynamicQueryEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("dynamicQueryEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			dynamicQueryEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(DynamicQueryEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"dynamicQueryEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			dynamicQueryEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DynamicQueryEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("dynamicQueryEntryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return dynamicQueryEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement DynamicQueryEntryLocalServiceImpl#deleteDynamicQueryEntry(DynamicQueryEntry) to avoid orphaned data");
		}

		return dynamicQueryEntryLocalService.deleteDynamicQueryEntry(
			(DynamicQueryEntry)persistedModel);
	}

	@Override
	public BasePersistence<DynamicQueryEntry> getBasePersistence() {
		return dynamicQueryEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return dynamicQueryEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the dynamic query entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.DynamicQueryEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of dynamic query entries
	 * @param end the upper bound of the range of dynamic query entries (not inclusive)
	 * @return the range of dynamic query entries
	 */
	@Override
	public List<DynamicQueryEntry> getDynamicQueryEntries(int start, int end) {
		return dynamicQueryEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of dynamic query entries.
	 *
	 * @return the number of dynamic query entries
	 */
	@Override
	public int getDynamicQueryEntriesCount() {
		return dynamicQueryEntryPersistence.countAll();
	}

	/**
	 * Updates the dynamic query entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DynamicQueryEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dynamicQueryEntry the dynamic query entry
	 * @return the dynamic query entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DynamicQueryEntry updateDynamicQueryEntry(
		DynamicQueryEntry dynamicQueryEntry) {

		return dynamicQueryEntryPersistence.update(dynamicQueryEntry);
	}

	/**
	 * Returns the dynamic query entry local service.
	 *
	 * @return the dynamic query entry local service
	 */
	public DynamicQueryEntryLocalService getDynamicQueryEntryLocalService() {
		return dynamicQueryEntryLocalService;
	}

	/**
	 * Sets the dynamic query entry local service.
	 *
	 * @param dynamicQueryEntryLocalService the dynamic query entry local service
	 */
	public void setDynamicQueryEntryLocalService(
		DynamicQueryEntryLocalService dynamicQueryEntryLocalService) {

		this.dynamicQueryEntryLocalService = dynamicQueryEntryLocalService;
	}

	/**
	 * Returns the dynamic query entry persistence.
	 *
	 * @return the dynamic query entry persistence
	 */
	public DynamicQueryEntryPersistence getDynamicQueryEntryPersistence() {
		return dynamicQueryEntryPersistence;
	}

	/**
	 * Sets the dynamic query entry persistence.
	 *
	 * @param dynamicQueryEntryPersistence the dynamic query entry persistence
	 */
	public void setDynamicQueryEntryPersistence(
		DynamicQueryEntryPersistence dynamicQueryEntryPersistence) {

		this.dynamicQueryEntryPersistence = dynamicQueryEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		DynamicQueryEntryLocalServiceUtil.setService(
			dynamicQueryEntryLocalService);
	}

	public void destroy() {
		DynamicQueryEntryLocalServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DynamicQueryEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return DynamicQueryEntry.class;
	}

	protected String getModelClassName() {
		return DynamicQueryEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = dynamicQueryEntryPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(type = DynamicQueryEntryLocalService.class)
	protected DynamicQueryEntryLocalService dynamicQueryEntryLocalService;

	@BeanReference(type = DynamicQueryEntryPersistence.class)
	protected DynamicQueryEntryPersistence dynamicQueryEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		DynamicQueryEntryLocalServiceBaseImpl.class);

}
// LIFERAY-SERVICE-BUILDER-HASH:-857423143