#
# This is a generated file.
#

api.version=v1.0
entity.class.name=com.liferay.cookies.rest.dto.v1_0.CookiesConsentPreference
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Cookies.REST)
osgi.jaxrs.resource=true