modified.files.includes[relevant][headless-admin-fragment-functional-rule]=**

modified.files.includes[relevant][headless-admin-fragment-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][headless-admin-fragment-java-rule]=\
    apps/headless/headless-admin-fragment/**/*Test.java

relevant.rule.names=headless-admin-fragment-java-rule

test.batch.names[relevant][headless-admin-fragment-java-rule]=\
    modules-integration-postgresql163

testray.main.component.name=Fragment Administration