java.util.logging.ConsoleHandler.level=FINE
java.util.logging.ConsoleHandler.formatter=co.elastic.logging.jul.EcsFormatter
java.util.logging.ConsoleHandler.encoding=UTF-8

co.elastic.logging.jul.EcsFormatter.additionalFields=source=tomcat,severity=INFO