modified.files.includes[relevant][rss-functional-rule]=**

modified.files.includes[relevant][rss-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-*][relevant][rss-java-rule]=\
    apps/asset/**/src/testIntegration/**/*Test.java,\
    apps/rss/**/src/testIntegration/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][rss-java-rule]=\
    apps/asset/**/src/test/**/*Test.java,\
    apps/rss/**/src/test/**/*Test.java

relevant.rule.names=\
    rss-functional-rule,\
    rss-java-rule

test.batch.names[relevant][rss-functional-rule]=\
    functional-upgrade-tomcat90-mysql84

test.batch.names[relevant][rss-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
    (portal.acceptance == true) AND \
    (\
        (testray.component.names ~ "Auto Tagging") OR \
        (testray.component.names ~ "Categories") OR \
        (testray.component.names ~ "Collections") OR \
        (testray.main.component.name ~ "Asset Publisher Widget") OR \
        (testray.main.component.name ~ "Auto Tagging") OR \
        (testray.main.component.name ~ "Categories") OR \
        (testray.main.component.name ~ "Collections") OR \
        (testray.main.component.name ~ "Localization") OR \
        (testray.main.component.name ~ "Message Boards") OR \
        (testray.main.component.name ~ "Recycle Bin") OR \
        (testray.main.component.name ~ "Related Assets Widget") OR \
        (testray.main.component.name ~ "Tags")\
    )

test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][rss-functional-rule]=\
    (portal.acceptance == true)

testray.main.component.name=RSS Publisher Widget