/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DynamicQueryEntry service. Represents a row in the &quot;DynamicQueryEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.DynamicQueryEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.DynamicQueryEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DynamicQueryEntry
 * @generated
 */
@ProviderType
public interface DynamicQueryEntryModel extends BaseModel<DynamicQueryEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dynamic query entry model instance should use the {@link DynamicQueryEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this dynamic query entry.
	 *
	 * @return the primary key of this dynamic query entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dynamic query entry.
	 *
	 * @param primaryKey the primary key of this dynamic query entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dynamic query entry ID of this dynamic query entry.
	 *
	 * @return the dynamic query entry ID of this dynamic query entry
	 */
	public long getDynamicQueryEntryId();

	/**
	 * Sets the dynamic query entry ID of this dynamic query entry.
	 *
	 * @param dynamicQueryEntryId the dynamic query entry ID of this dynamic query entry
	 */
	public void setDynamicQueryEntryId(long dynamicQueryEntryId);

	/**
	 * Returns the create date of this dynamic query entry.
	 *
	 * @return the create date of this dynamic query entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this dynamic query entry.
	 *
	 * @param createDate the create date of this dynamic query entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dynamic query entry.
	 *
	 * @return the modified date of this dynamic query entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dynamic query entry.
	 *
	 * @param modifiedDate the modified date of this dynamic query entry
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the amount of this dynamic query entry.
	 *
	 * @return the amount of this dynamic query entry
	 */
	public long getAmount();

	/**
	 * Sets the amount of this dynamic query entry.
	 *
	 * @param amount the amount of this dynamic query entry
	 */
	public void setAmount(long amount);

	/**
	 * Returns the description of this dynamic query entry.
	 *
	 * @return the description of this dynamic query entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this dynamic query entry.
	 *
	 * @param description the description of this dynamic query entry
	 */
	public void setDescription(String description);

	/**
	 * Returns the name of this dynamic query entry.
	 *
	 * @return the name of this dynamic query entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this dynamic query entry.
	 *
	 * @param name the name of this dynamic query entry
	 */
	public void setName(String name);

	/**
	 * Returns the status of this dynamic query entry.
	 *
	 * @return the status of this dynamic query entry
	 */
	public int getStatus();

	/**
	 * Sets the status of this dynamic query entry.
	 *
	 * @param status the status of this dynamic query entry
	 */
	public void setStatus(int status);

	@Override
	public DynamicQueryEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-1264789371