/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

const execa = require('execa');

module.exports = {
	customBuild: {
		esbuild: false,
		other: async () => {
			await execa('node', ['./clay/clay-css/scripts/build.js'], {
				stdio: 'inherit',
			});
		},
	},
	exports: [
		'@clayui/alert',
		'@clayui/autocomplete',
		'@clayui/badge',
		'@clayui/breadcrumb',
		'@clayui/button',
		'@clayui/card',
		'@clayui/charts',
		'@clayui/color-picker',
		'@clayui/core',
		'@clayui/data-provider',
		'@clayui/date-picker',
		'@clayui/drop-down',
		'@clayui/empty-state',
		'@clayui/form',
		'@clayui/icon',
		'@clayui/label',
		'@clayui/layout',
		'@clayui/link',
		'@clayui/list',
		'@clayui/loading-indicator',
		'@clayui/localized-input',
		'@clayui/management-toolbar',
		'@clayui/modal',
		'@clayui/multi-select',
		'@clayui/multi-step-nav',
		'@clayui/nav',
		'@clayui/navigation-bar',
		'@clayui/pagination',
		'@clayui/pagination-bar',
		'@clayui/panel',
		'@clayui/popover',
		'@clayui/progress-bar',
		'@clayui/provider',
		'@clayui/shared',
		'@clayui/slider',
		'@clayui/sticker',
		'@clayui/table',
		'@clayui/tabs',
		'@clayui/time-picker',
		'@clayui/toolbar',
		'@clayui/tooltip',
		'@clayui/upper-toolbar',
		'@clayui/css/lib/css/atlas.css',
		'@clayui/css/lib/css/base.css',
		'@clayui/css/lib/css/cadmin.css',
	],
	main: './src/main/resources/META-INF/resources/js/index.ts',
	symbols: {
		'@clayui/alert': ['DisplayType', 'IClayAlertProps', 'default'],
		'@clayui/autocomplete': ['Autocomplete', 'Item', 'default'],
		'@clayui/badge': ['default'],
		'@clayui/breadcrumb': ['default'],
		'@clayui/button': [
			'ButtonProps',
			'ButtonWithIconProps',
			'ClayButtonWithIcon',
			'default',
		],
		'@clayui/card': [
			'ClayCardWithHorizontal',
			'ClayCardWithInfo',
			'ClayCardWithNavigation',
			'ClayCardWithUser',
			'default',
		],
		'@clayui/charts': ['IProps', 'Types', 'bb', 'default'],
		'@clayui/color-picker': ['default'],
		'@clayui/core': [
			'AnnouncerAPI',
			'Body',
			'Button',
			'ButtonWithIcon',
			'Cell',
			'ColorType',
			'FocusTrap',
			'Head',
			'Heading',
			'ICollectionProps',
			'Icon',
			'IconSelector',
			'Item',
			'LanguagePicker',
			'Modal',
			'ModalContext',
			'Nav',
			'Option',
			'OverlayMask',
			'Picker',
			'Provider',
			'Row',
			'SidePanel',
			'SidePanelProps',
			'SidePanelWithDrilldown',
			'Table',
			'Text',
			'TextHighlight',
			'TreeView',
			'VerticalBar',
			'VerticalNav',
			'__EXPERIMENTAL_MENU',
			'__NOT_PUBLIC_COLLECTION',
			'__NOT_PUBLIC_LIVE_ANNOUNCER',
			'useModal',
			'useProvider',
		],
		'@clayui/data-provider': [
			'DataProvider',
			'FetchPolicy',
			'NetworkStatus',
			'Sorting',
			'default',
			'useResource',
		],
		'@clayui/date-picker': ['FirstDayOfWeek', 'default'],
		'@clayui/drop-down': [
			'Align',
			'ClayDropDownWithDrilldown',
			'ClayDropDownWithItems',
			'DropDown',
			'default',
		],
		'@clayui/empty-state': ['default'],
		'@clayui/form': [
			'ClayCheckbox',
			'ClayDualListBox',
			'ClayInput',
			'ClayRadio',
			'ClayRadioGroup',
			'ClaySelect',
			'ClaySelectBox',
			'ClaySelectWithOption',
			'ClayToggle',
			'default',
		],
		'@clayui/icon': ['ClayIconSpriteContext', 'default'],
		'@clayui/label': ['ItemAfter', 'ItemBefore', 'ItemExpand', 'default'],
		'@clayui/layout': [
			'Col',
			'Container',
			'ContainerFluid',
			'ContentCol',
			'ContentRow',
			'ContentSection',
			'Row',
			'Sheet',
			'SheetFooter',
			'SheetHeader',
			'SheetRow',
			'SheetSection',
			'default',
		],
		'@clayui/link': ['ClayLinkContext', 'default'],
		'@clayui/list': [
			'ClayListWithItems',
			'Header',
			'Item',
			'ItemText',
			'ItemTitle',
			'QuickActionMenu',
			'default',
		],
		'@clayui/loading-indicator': ['default'],
		'@clayui/localized-input': ['default'],
		'@clayui/management-toolbar': ['ClayResultsBar', 'default'],
		'@clayui/modal': [
			'Body',
			'ClayModalProvider',
			'Context',
			'Header',
			'Item',
			'ItemGroup',
			'Modal',
			'Subtitle',
			'SubtitleSection',
			'Title',
			'TitleIndicator',
			'TitleSection',
			'default',
			'useModal',
		],
		'@clayui/multi-select': ['IProps', 'default', 'itemLabelFilter'],
		'@clayui/multi-step-nav': ['ClayMultiStepNavWithBasicItems', 'default'],
		'@clayui/nav': ['ClayVerticalNav', 'default'],
		'@clayui/navigation-bar': ['IProps', 'default'],
		'@clayui/pagination': [
			'ClayPaginationWithBasicItems',
			'Ellipsis',
			'Item',
			'Pagination',
			'default',
		],
		'@clayui/pagination-bar': [
			'ClayPaginationBarWithBasicItems',
			'DropDown',
			'PaginationBar',
			'Results',
			'default',
		],
		'@clayui/panel': ['IProps', 'default'],
		'@clayui/popover': ['ALIGN_POSITIONS', 'Popover', 'default'],
		'@clayui/progress-bar': ['default'],
		'@clayui/provider': [
			'Provider',
			'__UNSTABLE_DataClient',
			'useProvider',
		],
		'@clayui/shared': [
			'AlignPoints',
			'ClayPortal',
			'FOCUSABLE_ELEMENTS',
			'FocusScope',
			'IPortalBaseProps',
			'InternalDispatch',
			'Keys',
			'LinkOrButton',
			'Locator',
			'MouseSafeArea',
			'Overlay',
			'PanelResizer',
			'Position',
			'delegate',
			'doAlign',
			'getEllipsisItems',
			'getFocusableList',
			'getLocatorValue',
			'isAppleDevice',
			'isIOS',
			'isIPad',
			'isIPhone',
			'isMac',
			'isTypeahead',
			'noop',
			'observeRect',
			'setElementFullHeight',
			'stack',
			'sub',
			'throttle',
			'useControlledState',
			'useDebounce',
			'useFocusManagement',
			'useFocusVisible',
			'useHover',
			'useId',
			'useInteractionFocus',
			'useIsFirstRender',
			'useIsMobileDevice',
			'useMousePosition',
			'useNavigation',
			'useOverlayPosition',
			'usePrevious',
		],
		'@clayui/slider': ['default'],
		'@clayui/sticker': ['DisplayType', 'IClayStickerProps', 'default'],
		'@clayui/table': ['IProps', 'default'],
		'@clayui/tabs': ['DisplayType', 'IProps', 'default'],
		'@clayui/time-picker': ['Input', 'InputAmPm', 'default'],
		'@clayui/toolbar': ['default'],
		'@clayui/tooltip': ['ClayTooltipProvider', 'Tooltip', 'default'],
		'@clayui/upper-toolbar': ['IInputProps', 'Input', 'Item', 'default'],
	},
};
