modified.files.includes[relevant][headless-admin-configuration-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][headless-admin-configuration-java-rule]=\
    apps/headless-admin-configuration/**/*Test.java

relevant.rule.names=headless-admin-configuration-java-rule

test.batch.names[relevant][headless-admin-configuration-java-rule]=\
    modules-integration-postgresql163

test.batch.run.property.query[functional-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
    (portal.acceptance == true) AND \
    (testray.main.component.name ~ "Headless Admin Configuration")

testray.main.component.name=Headless Admin Configuration