buildService {
	apiDir = "../osb-faro-api/src/main/java"
	databaseNameMaxLength = 64
}

dependencies {
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "com.sun.mail", name: "jakarta.mail", version: "1.6.8"
	compileOnly group: "junit", name: "junit", version: "4.13.1"
	compileOnly group: "org.apache.felix", name: "org.apache.felix.http.servlet-api", version: "1.1.2"
	compileOnly group: "org.osgi", name: "org.osgi.annotation.versioning", version: "1.1.0"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.4.0"
	compileOnly group: "org.osgi", name: "osgi.core", version: "6.0.0"
	compileOnly project(":apps:portal:portal-aop-api")
	compileOnly project(":apps:portal:portal-dao-orm-custom-sql-api")
	compileOnly project(":apps:portal:portal-spring-extender-api")
	compileOnly project(":apps:static:portal:portal-upgrade-api")
	compileOnly project(":core:petra:petra-function")
	compileOnly project(":core:petra:petra-lang")
	compileOnly project(":core:petra:petra-sql-dsl-api")
	compileOnly project(":core:petra:petra-string")
	compileOnly project(":dxp:apps:osb:osb-faro:osb-faro-api")
}