##
## Test Batch
##

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]=\
        (portal.acceptance == true) AND \
        (\
            (testray.main.component.name ~ "Templates") OR \
            (testray.main.component.name ~ "Templates Engine")\
        )

##
## Testray
##

    testray.main.component.name=Templates