##
## Backend Tests
##

    modules.includes.required[relevant]=\
        apps/portal-search,\
        apps/portal-search-elasticsearch7

##
## Functional Tests
##

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]=\
        (test.class.name == Blueprints) OR \
        (test.class.name == SemanticSearch)

    test.batch.run.property.query[functional-upgrade-tomcat*-mysql*-jdk8][relevant]=\
        (portal.suite.search.engine ~ "elasticsearch7") AND \
        (testray.main.component.name ~ "Upgrades Search")

##
## Testray
##

    testray.main.component.name=Search Experiences