argo:
    workflowSpec:
        podGC:
            strategy: OnWorkflowSuccess
        ttlStrategy:
            secondsAfterCompletion: 86400
images:
    gcloud:
        repository: google/cloud-sdk
        tag: 565.0.0-stable
    helmKubectl:
        repository: dtzar/helm-kubectl
        tag: 4.1.1
liferayInfrastructure:
    waitTimeoutSeconds: 3600
liferayWorkload:
    rolloutTimeout: 15m
resources:
    default:
        limits:
            cpu: 250m
            memory: 256Mi
        requests:
            cpu: 100m
            memory: 128Mi