/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.segments.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.change.tracking.CTModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SegmentsExperienceAudienceEntryRel service. Represents a row in the &quot;SExperienceAudienceEntryRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.segments.model.impl.SegmentsExperienceAudienceEntryRelModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.segments.model.impl.SegmentsExperienceAudienceEntryRelImpl</code>.
 * </p>
 *
 * @author Eduardo Garcia
 * @see SegmentsExperienceAudienceEntryRel
 * @generated
 */
@ProviderType
public interface SegmentsExperienceAudienceEntryRelModel
	extends BaseModel<SegmentsExperienceAudienceEntryRel>,
			CTModel<SegmentsExperienceAudienceEntryRel>, GroupedModel,
			MVCCModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a segments experience audience entry rel model instance should use the {@link SegmentsExperienceAudienceEntryRel} interface instead.
	 */

	/**
	 * Returns the primary key of this segments experience audience entry rel.
	 *
	 * @return the primary key of this segments experience audience entry rel
	 */
	@Override
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this segments experience audience entry rel.
	 *
	 * @param primaryKey the primary key of this segments experience audience entry rel
	 */
	@Override
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this segments experience audience entry rel.
	 *
	 * @return the mvcc version of this segments experience audience entry rel
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this segments experience audience entry rel.
	 *
	 * @param mvccVersion the mvcc version of this segments experience audience entry rel
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the ct collection ID of this segments experience audience entry rel.
	 *
	 * @return the ct collection ID of this segments experience audience entry rel
	 */
	@Override
	public long getCtCollectionId();

	/**
	 * Sets the ct collection ID of this segments experience audience entry rel.
	 *
	 * @param ctCollectionId the ct collection ID of this segments experience audience entry rel
	 */
	@Override
	public void setCtCollectionId(long ctCollectionId);

	/**
	 * Returns the uuid of this segments experience audience entry rel.
	 *
	 * @return the uuid of this segments experience audience entry rel
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this segments experience audience entry rel.
	 *
	 * @param uuid the uuid of this segments experience audience entry rel
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the segments experience audience entry rel ID of this segments experience audience entry rel.
	 *
	 * @return the segments experience audience entry rel ID of this segments experience audience entry rel
	 */
	public long getSegmentsExperienceAudienceEntryRelId();

	/**
	 * Sets the segments experience audience entry rel ID of this segments experience audience entry rel.
	 *
	 * @param segmentsExperienceAudienceEntryRelId the segments experience audience entry rel ID of this segments experience audience entry rel
	 */
	public void setSegmentsExperienceAudienceEntryRelId(
		long segmentsExperienceAudienceEntryRelId);

	/**
	 * Returns the group ID of this segments experience audience entry rel.
	 *
	 * @return the group ID of this segments experience audience entry rel
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this segments experience audience entry rel.
	 *
	 * @param groupId the group ID of this segments experience audience entry rel
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this segments experience audience entry rel.
	 *
	 * @return the company ID of this segments experience audience entry rel
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this segments experience audience entry rel.
	 *
	 * @param companyId the company ID of this segments experience audience entry rel
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this segments experience audience entry rel.
	 *
	 * @return the user ID of this segments experience audience entry rel
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this segments experience audience entry rel.
	 *
	 * @param userId the user ID of this segments experience audience entry rel
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this segments experience audience entry rel.
	 *
	 * @return the user uuid of this segments experience audience entry rel
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this segments experience audience entry rel.
	 *
	 * @param userUuid the user uuid of this segments experience audience entry rel
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this segments experience audience entry rel.
	 *
	 * @return the user name of this segments experience audience entry rel
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this segments experience audience entry rel.
	 *
	 * @param userName the user name of this segments experience audience entry rel
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this segments experience audience entry rel.
	 *
	 * @return the create date of this segments experience audience entry rel
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this segments experience audience entry rel.
	 *
	 * @param createDate the create date of this segments experience audience entry rel
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this segments experience audience entry rel.
	 *
	 * @return the modified date of this segments experience audience entry rel
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this segments experience audience entry rel.
	 *
	 * @param modifiedDate the modified date of this segments experience audience entry rel
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the audience entry erc of this segments experience audience entry rel.
	 *
	 * @return the audience entry erc of this segments experience audience entry rel
	 */
	@AutoEscape
	public String getAudienceEntryERC();

	/**
	 * Sets the audience entry erc of this segments experience audience entry rel.
	 *
	 * @param audienceEntryERC the audience entry erc of this segments experience audience entry rel
	 */
	public void setAudienceEntryERC(String audienceEntryERC);

	/**
	 * Returns the priority of this segments experience audience entry rel.
	 *
	 * @return the priority of this segments experience audience entry rel
	 */
	public int getPriority();

	/**
	 * Sets the priority of this segments experience audience entry rel.
	 *
	 * @param priority the priority of this segments experience audience entry rel
	 */
	public void setPriority(int priority);

	/**
	 * Returns the segments experience erc of this segments experience audience entry rel.
	 *
	 * @return the segments experience erc of this segments experience audience entry rel
	 */
	@AutoEscape
	public String getSegmentsExperienceERC();

	/**
	 * Sets the segments experience erc of this segments experience audience entry rel.
	 *
	 * @param segmentsExperienceERC the segments experience erc of this segments experience audience entry rel
	 */
	public void setSegmentsExperienceERC(String segmentsExperienceERC);

	@Override
	public SegmentsExperienceAudienceEntryRel cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-1795971729