/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.layout.page.template.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.layout.page.template.model.LayoutPageTemplateStructureRelElementVariation;
import com.liferay.layout.page.template.service.LayoutPageTemplateStructureRelElementVariationLocalService;
import com.liferay.layout.page.template.service.persistence.LayoutPageTemplateStructureRelElementVariationPersistence;
import com.liferay.petra.function.UnsafeFunction;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.change.tracking.CTService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.change.tracking.CTPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the layout page template structure rel element variation local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.layout.page.template.service.impl.LayoutPageTemplateStructureRelElementVariationLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.layout.page.template.service.impl.LayoutPageTemplateStructureRelElementVariationLocalServiceImpl
 * @generated
 */
public abstract class
	LayoutPageTemplateStructureRelElementVariationLocalServiceBaseImpl
		extends BaseLocalServiceImpl
		implements AopService, IdentifiableOSGiService,
				   LayoutPageTemplateStructureRelElementVariationLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>LayoutPageTemplateStructureRelElementVariationLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.layout.page.template.service.LayoutPageTemplateStructureRelElementVariationLocalServiceUtil</code>.
	 */

	/**
	 * Adds the layout page template structure rel element variation to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LayoutPageTemplateStructureRelElementVariationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param layoutPageTemplateStructureRelElementVariation the layout page template structure rel element variation
	 * @return the layout page template structure rel element variation that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LayoutPageTemplateStructureRelElementVariation
		addLayoutPageTemplateStructureRelElementVariation(
			LayoutPageTemplateStructureRelElementVariation
				layoutPageTemplateStructureRelElementVariation) {

		layoutPageTemplateStructureRelElementVariation.setNew(true);

		return layoutPageTemplateStructureRelElementVariationPersistence.update(
			layoutPageTemplateStructureRelElementVariation);
	}

	/**
	 * Creates a new layout page template structure rel element variation with the primary key. Does not add the layout page template structure rel element variation to the database.
	 *
	 * @param layoutPageTemplateStructureRelElementVariationId the primary key for the new layout page template structure rel element variation
	 * @return the new layout page template structure rel element variation
	 */
	@Override
	@Transactional(enabled = false)
	public LayoutPageTemplateStructureRelElementVariation
		createLayoutPageTemplateStructureRelElementVariation(
			long layoutPageTemplateStructureRelElementVariationId) {

		return layoutPageTemplateStructureRelElementVariationPersistence.create(
			layoutPageTemplateStructureRelElementVariationId);
	}

	/**
	 * Deletes the layout page template structure rel element variation with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LayoutPageTemplateStructureRelElementVariationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param layoutPageTemplateStructureRelElementVariationId the primary key of the layout page template structure rel element variation
	 * @return the layout page template structure rel element variation that was removed
	 * @throws PortalException if a layout page template structure rel element variation with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LayoutPageTemplateStructureRelElementVariation
			deleteLayoutPageTemplateStructureRelElementVariation(
				long layoutPageTemplateStructureRelElementVariationId)
		throws PortalException {

		return layoutPageTemplateStructureRelElementVariationPersistence.remove(
			layoutPageTemplateStructureRelElementVariationId);
	}

	/**
	 * Deletes the layout page template structure rel element variation from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LayoutPageTemplateStructureRelElementVariationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param layoutPageTemplateStructureRelElementVariation the layout page template structure rel element variation
	 * @return the layout page template structure rel element variation that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LayoutPageTemplateStructureRelElementVariation
		deleteLayoutPageTemplateStructureRelElementVariation(
			LayoutPageTemplateStructureRelElementVariation
				layoutPageTemplateStructureRelElementVariation) {

		return layoutPageTemplateStructureRelElementVariationPersistence.remove(
			layoutPageTemplateStructureRelElementVariation);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return layoutPageTemplateStructureRelElementVariationPersistence.
			dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			LayoutPageTemplateStructureRelElementVariation.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return layoutPageTemplateStructureRelElementVariationPersistence.
			findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.layout.page.template.model.impl.LayoutPageTemplateStructureRelElementVariationModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return layoutPageTemplateStructureRelElementVariationPersistence.
			findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.layout.page.template.model.impl.LayoutPageTemplateStructureRelElementVariationModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return layoutPageTemplateStructureRelElementVariationPersistence.
			findWithDynamicQuery(dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return layoutPageTemplateStructureRelElementVariationPersistence.
			countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return layoutPageTemplateStructureRelElementVariationPersistence.
			countWithDynamicQuery(dynamicQuery, projection);
	}

	@Override
	public LayoutPageTemplateStructureRelElementVariation
		fetchLayoutPageTemplateStructureRelElementVariation(
			long layoutPageTemplateStructureRelElementVariationId) {

		return layoutPageTemplateStructureRelElementVariationPersistence.
			fetchByPrimaryKey(layoutPageTemplateStructureRelElementVariationId);
	}

	/**
	 * Returns the layout page template structure rel element variation matching the UUID and group.
	 *
	 * @param uuid the layout page template structure rel element variation's UUID
	 * @param groupId the primary key of the group
	 * @return the matching layout page template structure rel element variation, or <code>null</code> if a matching layout page template structure rel element variation could not be found
	 */
	@Override
	public LayoutPageTemplateStructureRelElementVariation
		fetchLayoutPageTemplateStructureRelElementVariationByUuidAndGroupId(
			String uuid, long groupId) {

		return layoutPageTemplateStructureRelElementVariationPersistence.
			fetchByUUID_G(uuid, groupId);
	}

	@Override
	public LayoutPageTemplateStructureRelElementVariation
		fetchLayoutPageTemplateStructureRelElementVariationByExternalReferenceCode(
			String externalReferenceCode, long groupId) {

		return layoutPageTemplateStructureRelElementVariationPersistence.
			fetchByERC_G(externalReferenceCode, groupId);
	}

	@Override
	public LayoutPageTemplateStructureRelElementVariation
			getLayoutPageTemplateStructureRelElementVariationByExternalReferenceCode(
				String externalReferenceCode, long groupId)
		throws PortalException {

		return layoutPageTemplateStructureRelElementVariationPersistence.
			findByERC_G(externalReferenceCode, groupId);
	}

	/**
	 * Returns the layout page template structure rel element variation with the primary key.
	 *
	 * @param layoutPageTemplateStructureRelElementVariationId the primary key of the layout page template structure rel element variation
	 * @return the layout page template structure rel element variation
	 * @throws PortalException if a layout page template structure rel element variation with the primary key could not be found
	 */
	@Override
	public LayoutPageTemplateStructureRelElementVariation
			getLayoutPageTemplateStructureRelElementVariation(
				long layoutPageTemplateStructureRelElementVariationId)
		throws PortalException {

		return layoutPageTemplateStructureRelElementVariationPersistence.
			findByPrimaryKey(layoutPageTemplateStructureRelElementVariationId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			layoutPageTemplateStructureRelElementVariationLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			LayoutPageTemplateStructureRelElementVariation.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"layoutPageTemplateStructureRelElementVariationId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			layoutPageTemplateStructureRelElementVariationLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			LayoutPageTemplateStructureRelElementVariation.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"layoutPageTemplateStructureRelElementVariationId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			layoutPageTemplateStructureRelElementVariationLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			LayoutPageTemplateStructureRelElementVariation.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"layoutPageTemplateStructureRelElementVariationId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<LayoutPageTemplateStructureRelElementVariation>() {

				@Override
				public void performAction(
						LayoutPageTemplateStructureRelElementVariation
							layoutPageTemplateStructureRelElementVariation)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext,
						layoutPageTemplateStructureRelElementVariation);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					LayoutPageTemplateStructureRelElementVariation.class.
						getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return layoutPageTemplateStructureRelElementVariationPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement LayoutPageTemplateStructureRelElementVariationLocalServiceImpl#deleteLayoutPageTemplateStructureRelElementVariation(LayoutPageTemplateStructureRelElementVariation) to avoid orphaned data");
		}

		return layoutPageTemplateStructureRelElementVariationLocalService.
			deleteLayoutPageTemplateStructureRelElementVariation(
				(LayoutPageTemplateStructureRelElementVariation)persistedModel);
	}

	@Override
	public BasePersistence<LayoutPageTemplateStructureRelElementVariation>
		getBasePersistence() {

		return layoutPageTemplateStructureRelElementVariationPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return layoutPageTemplateStructureRelElementVariationPersistence.
			findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the layout page template structure rel element variations matching the UUID and company.
	 *
	 * @param uuid the UUID of the layout page template structure rel element variations
	 * @param companyId the primary key of the company
	 * @return the matching layout page template structure rel element variations, or an empty list if no matches were found
	 */
	@Override
	public List<LayoutPageTemplateStructureRelElementVariation>
		getLayoutPageTemplateStructureRelElementVariationsByUuidAndCompanyId(
			String uuid, long companyId) {

		return layoutPageTemplateStructureRelElementVariationPersistence.
			findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of layout page template structure rel element variations matching the UUID and company.
	 *
	 * @param uuid the UUID of the layout page template structure rel element variations
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of layout page template structure rel element variations
	 * @param end the upper bound of the range of layout page template structure rel element variations (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching layout page template structure rel element variations, or an empty list if no matches were found
	 */
	@Override
	public List<LayoutPageTemplateStructureRelElementVariation>
		getLayoutPageTemplateStructureRelElementVariationsByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator<LayoutPageTemplateStructureRelElementVariation>
				orderByComparator) {

		return layoutPageTemplateStructureRelElementVariationPersistence.
			findByUuid_C(uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the layout page template structure rel element variation matching the UUID and group.
	 *
	 * @param uuid the layout page template structure rel element variation's UUID
	 * @param groupId the primary key of the group
	 * @return the matching layout page template structure rel element variation
	 * @throws PortalException if a matching layout page template structure rel element variation could not be found
	 */
	@Override
	public LayoutPageTemplateStructureRelElementVariation
			getLayoutPageTemplateStructureRelElementVariationByUuidAndGroupId(
				String uuid, long groupId)
		throws PortalException {

		return layoutPageTemplateStructureRelElementVariationPersistence.
			findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the layout page template structure rel element variations.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.layout.page.template.model.impl.LayoutPageTemplateStructureRelElementVariationModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of layout page template structure rel element variations
	 * @param end the upper bound of the range of layout page template structure rel element variations (not inclusive)
	 * @return the range of layout page template structure rel element variations
	 */
	@Override
	public List<LayoutPageTemplateStructureRelElementVariation>
		getLayoutPageTemplateStructureRelElementVariations(int start, int end) {

		return layoutPageTemplateStructureRelElementVariationPersistence.
			findAll(start, end);
	}

	/**
	 * Returns the number of layout page template structure rel element variations.
	 *
	 * @return the number of layout page template structure rel element variations
	 */
	@Override
	public int getLayoutPageTemplateStructureRelElementVariationsCount() {
		return layoutPageTemplateStructureRelElementVariationPersistence.
			countAll();
	}

	/**
	 * Updates the layout page template structure rel element variation in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LayoutPageTemplateStructureRelElementVariationLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param layoutPageTemplateStructureRelElementVariation the layout page template structure rel element variation
	 * @return the layout page template structure rel element variation that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LayoutPageTemplateStructureRelElementVariation
		updateLayoutPageTemplateStructureRelElementVariation(
			LayoutPageTemplateStructureRelElementVariation
				layoutPageTemplateStructureRelElementVariation) {

		return layoutPageTemplateStructureRelElementVariationPersistence.update(
			layoutPageTemplateStructureRelElementVariation);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			LayoutPageTemplateStructureRelElementVariationLocalService.class,
			IdentifiableOSGiService.class, CTService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		layoutPageTemplateStructureRelElementVariationLocalService =
			(LayoutPageTemplateStructureRelElementVariationLocalService)
				aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return LayoutPageTemplateStructureRelElementVariationLocalService.class.
			getName();
	}

	@Override
	public CTPersistence<LayoutPageTemplateStructureRelElementVariation>
		getCTPersistence() {

		return layoutPageTemplateStructureRelElementVariationPersistence;
	}

	@Override
	public Class<LayoutPageTemplateStructureRelElementVariation>
		getModelClass() {

		return LayoutPageTemplateStructureRelElementVariation.class;
	}

	@Override
	public <R, E extends Throwable> R updateWithUnsafeFunction(
			UnsafeFunction
				<CTPersistence<LayoutPageTemplateStructureRelElementVariation>,
				 R, E> updateUnsafeFunction)
		throws E {

		return updateUnsafeFunction.apply(
			layoutPageTemplateStructureRelElementVariationPersistence);
	}

	protected String getModelClassName() {
		return LayoutPageTemplateStructureRelElementVariation.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource =
			layoutPageTemplateStructureRelElementVariationPersistence.
				getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected LayoutPageTemplateStructureRelElementVariationLocalService
		layoutPageTemplateStructureRelElementVariationLocalService;

	@Reference
	protected LayoutPageTemplateStructureRelElementVariationPersistence
		layoutPageTemplateStructureRelElementVariationPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		LayoutPageTemplateStructureRelElementVariationLocalServiceBaseImpl.
			class);

}
// LIFERAY-SERVICE-BUILDER-HASH:749194144