#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay-seostudio-etc-pagespeed-oahs.oauth2.headless.server.client.secret=${LIFERAY_SEOSTUDIO_ETC_PAGESPEED_OAHS_CLIENT_SECRET:myfancypassword}

liferay.oauth.application.external.reference.codes=\
    liferay-seostudio-etc-pagespeed-oahs,\
    liferay-seostudio-etc-pagespeed-oaua

liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#

server.port=58081