modified.files.includes[relevant][portal-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][portal-java-rule]=\
    apps/portal/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][portal-java-rule]=\
    apps/portal/**/*Test.java

relevant.rule.names=portal-java-rule

test.batch.names[relevant][portal-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
    (\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Document Management") OR \
            (testray.main.component.name == "Forms") OR \
            (testray.main.component.name ~ "Document Management")\
        )\
    ) OR \
    (testray.main.component.name == "Bundle Blacklist") OR \
    (\
        (license.required != "true") AND \
        (testray.main.component.name == "Clustering")\
    )

testray.main.component.name=Portal Services