##
## Playwright
##

    playwright.test.project[playwright-js-tomcat90-mysql57-jdk8][relevant]=object

##
## Test Batch
##

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]}

    #
    # Relevant
    #

    test.batch.class.names.includes[relevant]=\
        **/headless-builder/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names == "Headless Builder") OR \
            (testray.component.names == "Object") OR \
            (testray.main.component.name == "Headless Builder") OR \
            (testray.main.component.name == "Object")\
        )

##
## Testray
##

    testray.main.component.name=Object