modified.files.includes[relevant][site-teams-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql84][relevant][site-teams-web-playwright-rule]=\
    site-teams-web.main

relevant.rule.names=site-teams-web-playwright-rule

test.batch.names[relevant][site-teams-web-playwright-rule]=\
    playwright-js-tomcat101-mysql84

testray.main.component.name=Site Teams