{{- if .Values.alerting.notificationChannels -}}
apiVersion: v1
data:
    contact-points.yaml: |
        apiVersion: 1
        contactPoints:
            {{- range $key, $channel := .Values.alerting.notificationChannels }}
            {{- if not (eq $channel.enabled false) }}
            -   name: {{ $key }}
                receivers:
                    -   disableResolveMessage: {{ if hasKey $channel "disableResolveMessage" }}{{ index $channel "disableResolveMessage" }}{{ else }}true{{ end }}
                        {{- with $channel.settings }}
                        settings:
                            {{- toYaml . | nindent 28 }}
                        {{- end }}
                        type: {{ $channel.type | default "email" }}
                        uid: {{ $key }}
            {{- end }}
            {{- end }}
kind: ConfigMap
metadata:
    labels:
        {{- include "observability.labels" . | nindent 8 }}
        grafana_alert: "true"
    name: {{ printf "%s-contact-points" (include "observability.fullname" .) | trunc 63 | trimSuffix "-" | quote }}
    namespace: {{ include "observability.namespace" . | quote }}
{{- end -}}