/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

export const PENDING_ORDERS_FDS_NAME =
	'com_liferay_commerce_order_content_web_internal_fragment_renderer_OrdersDataSetFragmentRenderer-pendingOrders';

export const PENDING_ORDER_ITEMS_FDS_NAME =
	'com_liferay_commerce_order_content_web_internal_fragment_renderer_OrderItemsDataSetFragmentRenderer-pendingOrderItems';

export const PLACED_ORDERS_FDS_NAME =
	'com_liferay_commerce_order_content_web_internal_fragment_renderer_OrdersDataSetFragmentRenderer-placedOrders';

export const PLACED_ORDER_ATTACHMENTS_FDS_NAME =
	'com_liferay_commerce_order_content_web_internal_fragment_renderer_OrderAttachmentsDataSetFragmentRenderer-placedOrderAttachments';

export const PLACED_ORDER_ITEMS_FDS_NAME =
	'com_liferay_commerce_order_content_web_internal_fragment_renderer_OrderItemsDataSetFragmentRenderer-placedOrderItems';

export const PLACED_ORDER_RETURNS_FDS_NAME =
	'com_liferay_commerce_order_content_web_internal_fragment_renderer_OrderReturnsDataSetFragmentRenderer-placedOrderReturns';

export const PLACED_ORDER_SHIPMENTS_FDS_NAME =
	'com_liferay_commerce_order_content_web_internal_fragment_renderer_OrdersDataSetFragmentRenderer-placedOrderShipments';
