modified.files.includes[relevant][sharing-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][sharing-java-rule]=\
    apps/sharing/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][sharing-java-rule]=\
    apps/sharing/**/*Test.java

relevant.rule.names=sharing-java-rule

test.batch.names[relevant][sharing-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
    (portal.acceptance == true) AND \
    (\
        (testray.component.names ~ "Asset Sharing") OR \
        (testray.main.component.name ~ "Asset Sharing")\
    )

testray.main.component.name=Asset Sharing