##
## Modules
##

    modules.includes.required.test.batch.class.names.includes[relevant]=\
        (apps/portal-security/portal-security-permission-test/**/*Test.java)

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Depot") OR \
            (testray.main.component.name ~ "Depot")\
        )

##
## Testray
##

    testray.main.component.name=Depot