##
## Test Batch
##

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Simulation") OR \
            (testray.main.component.name ~ "Control Menu") OR \
            (testray.main.component.name ~ "Page Administration") OR \
            (testray.main.component.name ~ "Pages Tree") OR \
            (testray.main.component.name ~ "Sites Administration")\
        )

##
## Testray
##

    testray.main.component.name=Control Menu