modified.files.includes[relevant][frontend-css-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][frontend-css-java-rule]=\
    apps/frontend-css/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][frontend-css-java-rule]=\
    apps/frontend-css/**/*Test.java

playwright.projects.includes[playwright-js-tomcat101-postgresql163][relevant][frontend-css-cadmin-web-playwright-rule]=\
    frontend-css-cadmin-web.main

relevant.rule.names=frontend-css-java-rule

test.batch.names[relevant][frontend-css-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
    (environment.acceptance == true) AND \
    (portal.acceptance == true) AND \
    (portal.upstream == true) AND \
    (\
        (app.server.types == null) OR \
        (app.server.types ~ "tomcat")\
    ) AND \
    (\
        (database.types == null) OR \
        (database.types ~ "mysql")\
    ) AND \
    (\
        (operating.system.types == null) OR \
        (operating.system.types ~ "centos")\
    )

testray.main.component.name=Liferay Themes