/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.layout.content.model.impl;

import com.liferay.layout.content.model.LayoutContentVersion;
import com.liferay.layout.content.service.LayoutContentVersionLocalServiceUtil;

/**
 * The extended model base implementation for the LayoutContentVersion service. Represents a row in the &quot;LayoutContentVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LayoutContentVersionImpl}.
 * </p>
 *
 * @author Lourdes Fernández Besada
 * @see LayoutContentVersionImpl
 * @see LayoutContentVersion
 * @generated
 */
public abstract class LayoutContentVersionBaseImpl
	extends LayoutContentVersionModelImpl implements LayoutContentVersion {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a layout content version model instance should use the <code>LayoutContentVersion</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			LayoutContentVersionLocalServiceUtil.addLayoutContentVersion(this);
		}
		else {
			LayoutContentVersionLocalServiceUtil.updateLayoutContentVersion(
				this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-1004187592