/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.layout.content.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.layout.content.model.LayoutContentVersion;
import com.liferay.layout.content.model.LayoutContentVersionModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LayoutContentVersion service. Represents a row in the &quot;LayoutContentVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LayoutContentVersionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LayoutContentVersionImpl}.
 * </p>
 *
 * @author Lourdes Fernández Besada
 * @see LayoutContentVersionImpl
 * @generated
 */
@JSON(strict = true)
public class LayoutContentVersionModelImpl
	extends BaseModelImpl<LayoutContentVersion>
	implements LayoutContentVersionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a layout content version model instance should use the <code>LayoutContentVersion</code> interface instead.
	 */
	public static final String TABLE_NAME = "LayoutContentVersion";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"externalReferenceCode", Types.VARCHAR},
		{"layoutContentVersionId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"data_", Types.CLOB},
		{"dataHash", Types.VARCHAR}, {"name", Types.VARCHAR},
		{"plid", Types.BIGINT}, {"specSchemaVersion", Types.VARCHAR},
		{"version", Types.INTEGER}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("layoutContentVersionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("data_", Types.CLOB);
		TABLE_COLUMNS_MAP.put("dataHash", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("plid", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("specSchemaVersion", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("version", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LayoutContentVersion (mvccVersion LONG default 0 not null,externalReferenceCode VARCHAR(75) null,layoutContentVersionId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,data_ TEXT null,dataHash VARCHAR(75) null,name STRING null,plid LONG,specSchemaVersion VARCHAR(75) null,version INTEGER,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table LayoutContentVersion";

	public static final String ENTITY_ALIAS = "layoutContentVersion";

	public static final String ORDER_BY_JPQL =
		" ORDER BY layoutContentVersion.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LayoutContentVersion.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DATAHASH_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PLID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long VERSION_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public LayoutContentVersionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _layoutContentVersionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLayoutContentVersionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _layoutContentVersionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LayoutContentVersion.class;
	}

	@Override
	public String getModelClassName() {
		return LayoutContentVersion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LayoutContentVersion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LayoutContentVersion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LayoutContentVersion, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LayoutContentVersion)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LayoutContentVersion, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LayoutContentVersion, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LayoutContentVersion)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LayoutContentVersion, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LayoutContentVersion, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<LayoutContentVersion, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<LayoutContentVersion, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<LayoutContentVersion, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", LayoutContentVersion::getMvccVersion);
			attributeGetterFunctions.put(
				"externalReferenceCode",
				LayoutContentVersion::getExternalReferenceCode);
			attributeGetterFunctions.put(
				"layoutContentVersionId",
				LayoutContentVersion::getLayoutContentVersionId);
			attributeGetterFunctions.put(
				"groupId", LayoutContentVersion::getGroupId);
			attributeGetterFunctions.put(
				"companyId", LayoutContentVersion::getCompanyId);
			attributeGetterFunctions.put(
				"userId", LayoutContentVersion::getUserId);
			attributeGetterFunctions.put(
				"userName", LayoutContentVersion::getUserName);
			attributeGetterFunctions.put(
				"createDate", LayoutContentVersion::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", LayoutContentVersion::getModifiedDate);
			attributeGetterFunctions.put("data", LayoutContentVersion::getData);
			attributeGetterFunctions.put(
				"dataHash", LayoutContentVersion::getDataHash);
			attributeGetterFunctions.put("name", LayoutContentVersion::getName);
			attributeGetterFunctions.put("plid", LayoutContentVersion::getPlid);
			attributeGetterFunctions.put(
				"specSchemaVersion",
				LayoutContentVersion::getSpecSchemaVersion);
			attributeGetterFunctions.put(
				"version", LayoutContentVersion::getVersion);
			attributeGetterFunctions.put(
				"status", LayoutContentVersion::getStatus);
			attributeGetterFunctions.put(
				"statusByUserId", LayoutContentVersion::getStatusByUserId);
			attributeGetterFunctions.put(
				"statusByUserName", LayoutContentVersion::getStatusByUserName);
			attributeGetterFunctions.put(
				"statusDate", LayoutContentVersion::getStatusDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<LayoutContentVersion, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<LayoutContentVersion, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<LayoutContentVersion, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<LayoutContentVersion, Long>)
					LayoutContentVersion::setMvccVersion);
			attributeSetterBiConsumers.put(
				"externalReferenceCode",
				(BiConsumer<LayoutContentVersion, String>)
					LayoutContentVersion::setExternalReferenceCode);
			attributeSetterBiConsumers.put(
				"layoutContentVersionId",
				(BiConsumer<LayoutContentVersion, Long>)
					LayoutContentVersion::setLayoutContentVersionId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<LayoutContentVersion, Long>)
					LayoutContentVersion::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<LayoutContentVersion, Long>)
					LayoutContentVersion::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<LayoutContentVersion, Long>)
					LayoutContentVersion::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<LayoutContentVersion, String>)
					LayoutContentVersion::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<LayoutContentVersion, Date>)
					LayoutContentVersion::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<LayoutContentVersion, Date>)
					LayoutContentVersion::setModifiedDate);
			attributeSetterBiConsumers.put(
				"data",
				(BiConsumer<LayoutContentVersion, String>)
					LayoutContentVersion::setData);
			attributeSetterBiConsumers.put(
				"dataHash",
				(BiConsumer<LayoutContentVersion, String>)
					LayoutContentVersion::setDataHash);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<LayoutContentVersion, String>)
					LayoutContentVersion::setName);
			attributeSetterBiConsumers.put(
				"plid",
				(BiConsumer<LayoutContentVersion, Long>)
					LayoutContentVersion::setPlid);
			attributeSetterBiConsumers.put(
				"specSchemaVersion",
				(BiConsumer<LayoutContentVersion, String>)
					LayoutContentVersion::setSpecSchemaVersion);
			attributeSetterBiConsumers.put(
				"version",
				(BiConsumer<LayoutContentVersion, Integer>)
					LayoutContentVersion::setVersion);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<LayoutContentVersion, Integer>)
					LayoutContentVersion::setStatus);
			attributeSetterBiConsumers.put(
				"statusByUserId",
				(BiConsumer<LayoutContentVersion, Long>)
					LayoutContentVersion::setStatusByUserId);
			attributeSetterBiConsumers.put(
				"statusByUserName",
				(BiConsumer<LayoutContentVersion, String>)
					LayoutContentVersion::setStatusByUserName);
			attributeSetterBiConsumers.put(
				"statusDate",
				(BiConsumer<LayoutContentVersion, Date>)
					LayoutContentVersion::setStatusDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalReferenceCode = externalReferenceCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalExternalReferenceCode() {
		return getColumnOriginalValue("externalReferenceCode");
	}

	@JSON
	@Override
	public long getLayoutContentVersionId() {
		return _layoutContentVersionId;
	}

	@Override
	public void setLayoutContentVersionId(long layoutContentVersionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_layoutContentVersionId = layoutContentVersionId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getData() {
		if (_data == null) {
			return "";
		}
		else {
			return _data;
		}
	}

	@Override
	public void setData(String data) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_data = data;
	}

	@JSON
	@Override
	public String getDataHash() {
		if (_dataHash == null) {
			return "";
		}
		else {
			return _dataHash;
		}
	}

	@Override
	public void setDataHash(String dataHash) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataHash = dataHash;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalDataHash() {
		return getColumnOriginalValue("dataHash");
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public String getName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId);
	}

	@Override
	public String getName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId, useDefault);
	}

	@Override
	public String getName(String languageId) {
		return LocalizationUtil.getLocalization(getName(), languageId);
	}

	@Override
	public String getName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getName(), languageId, useDefault);
	}

	@Override
	public String getNameCurrentLanguageId() {
		return _nameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getNameCurrentValue() {
		Locale locale = getLocale(_nameCurrentLanguageId);

		return getName(locale);
	}

	@Override
	public Map<Locale, String> getNameMap() {
		return LocalizationUtil.getLocalizationMap(getName());
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@Override
	public void setName(String name, Locale locale) {
		setName(name, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setName(String name, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(name)) {
			setName(
				LocalizationUtil.updateLocalization(
					getName(), "Name", name, languageId, defaultLanguageId));
		}
		else {
			setName(
				LocalizationUtil.removeLocalization(
					getName(), "Name", languageId));
		}
	}

	@Override
	public void setNameCurrentLanguageId(String languageId) {
		_nameCurrentLanguageId = languageId;
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap) {
		setNameMap(nameMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale) {
		if (nameMap == null) {
			return;
		}

		setName(
			LocalizationUtil.updateLocalization(
				nameMap, getName(), "Name",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public long getPlid() {
		return _plid;
	}

	@Override
	public void setPlid(long plid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_plid = plid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPlid() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("plid"));
	}

	@JSON
	@Override
	public String getSpecSchemaVersion() {
		if (_specSchemaVersion == null) {
			return "";
		}
		else {
			return _specSchemaVersion;
		}
	}

	@Override
	public void setSpecSchemaVersion(String specSchemaVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_specSchemaVersion = specSchemaVersion;
	}

	@JSON
	@Override
	public int getVersion() {
		return _version;
	}

	@Override
	public void setVersion(int version) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_version = version;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalVersion() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("version"));
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LayoutContentVersion.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> nameMap = getNameMap();

		for (Map.Entry<Locale, String> entry : nameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			LayoutContentVersion.class.getName(), getPrimaryKey(),
			defaultLocale, availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String name = getName(defaultLocale);

		if (Validator.isNull(name)) {
			setName(getName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setName(getName(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public LayoutContentVersion toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LayoutContentVersion>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LayoutContentVersionImpl layoutContentVersionImpl =
			new LayoutContentVersionImpl();

		layoutContentVersionImpl.setMvccVersion(getMvccVersion());
		layoutContentVersionImpl.setExternalReferenceCode(
			getExternalReferenceCode());
		layoutContentVersionImpl.setLayoutContentVersionId(
			getLayoutContentVersionId());
		layoutContentVersionImpl.setGroupId(getGroupId());
		layoutContentVersionImpl.setCompanyId(getCompanyId());
		layoutContentVersionImpl.setUserId(getUserId());
		layoutContentVersionImpl.setUserName(getUserName());
		layoutContentVersionImpl.setCreateDate(getCreateDate());
		layoutContentVersionImpl.setModifiedDate(getModifiedDate());
		layoutContentVersionImpl.setData(getData());
		layoutContentVersionImpl.setDataHash(getDataHash());
		layoutContentVersionImpl.setName(getName());
		layoutContentVersionImpl.setPlid(getPlid());
		layoutContentVersionImpl.setSpecSchemaVersion(getSpecSchemaVersion());
		layoutContentVersionImpl.setVersion(getVersion());
		layoutContentVersionImpl.setStatus(getStatus());
		layoutContentVersionImpl.setStatusByUserId(getStatusByUserId());
		layoutContentVersionImpl.setStatusByUserName(getStatusByUserName());
		layoutContentVersionImpl.setStatusDate(getStatusDate());

		layoutContentVersionImpl.resetOriginalValues();

		return layoutContentVersionImpl;
	}

	@Override
	public LayoutContentVersion cloneWithOriginalValues() {
		LayoutContentVersionImpl layoutContentVersionImpl =
			new LayoutContentVersionImpl();

		layoutContentVersionImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		layoutContentVersionImpl.setExternalReferenceCode(
			this.<String>getColumnOriginalValue("externalReferenceCode"));
		layoutContentVersionImpl.setLayoutContentVersionId(
			this.<Long>getColumnOriginalValue("layoutContentVersionId"));
		layoutContentVersionImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		layoutContentVersionImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		layoutContentVersionImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		layoutContentVersionImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		layoutContentVersionImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		layoutContentVersionImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		layoutContentVersionImpl.setData(
			this.<String>getColumnOriginalValue("data_"));
		layoutContentVersionImpl.setDataHash(
			this.<String>getColumnOriginalValue("dataHash"));
		layoutContentVersionImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		layoutContentVersionImpl.setPlid(
			this.<Long>getColumnOriginalValue("plid"));
		layoutContentVersionImpl.setSpecSchemaVersion(
			this.<String>getColumnOriginalValue("specSchemaVersion"));
		layoutContentVersionImpl.setVersion(
			this.<Integer>getColumnOriginalValue("version"));
		layoutContentVersionImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		layoutContentVersionImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		layoutContentVersionImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		layoutContentVersionImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));

		return layoutContentVersionImpl;
	}

	@Override
	public int compareTo(LayoutContentVersion layoutContentVersion) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), layoutContentVersion.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LayoutContentVersion)) {
			return false;
		}

		LayoutContentVersion layoutContentVersion =
			(LayoutContentVersion)object;

		long primaryKey = layoutContentVersion.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LayoutContentVersion> toCacheModel() {
		LayoutContentVersionCacheModel layoutContentVersionCacheModel =
			new LayoutContentVersionCacheModel();

		layoutContentVersionCacheModel.mvccVersion = getMvccVersion();

		layoutContentVersionCacheModel.externalReferenceCode =
			getExternalReferenceCode();

		String externalReferenceCode =
			layoutContentVersionCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			layoutContentVersionCacheModel.externalReferenceCode = null;
		}

		layoutContentVersionCacheModel.layoutContentVersionId =
			getLayoutContentVersionId();

		layoutContentVersionCacheModel.groupId = getGroupId();

		layoutContentVersionCacheModel.companyId = getCompanyId();

		layoutContentVersionCacheModel.userId = getUserId();

		layoutContentVersionCacheModel.userName = getUserName();

		String userName = layoutContentVersionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			layoutContentVersionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			layoutContentVersionCacheModel.createDate = createDate.getTime();
		}
		else {
			layoutContentVersionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			layoutContentVersionCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			layoutContentVersionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		layoutContentVersionCacheModel.data = getData();

		String data = layoutContentVersionCacheModel.data;

		if ((data != null) && (data.length() == 0)) {
			layoutContentVersionCacheModel.data = null;
		}

		layoutContentVersionCacheModel.dataHash = getDataHash();

		String dataHash = layoutContentVersionCacheModel.dataHash;

		if ((dataHash != null) && (dataHash.length() == 0)) {
			layoutContentVersionCacheModel.dataHash = null;
		}

		layoutContentVersionCacheModel.name = getName();

		String name = layoutContentVersionCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			layoutContentVersionCacheModel.name = null;
		}

		layoutContentVersionCacheModel.plid = getPlid();

		layoutContentVersionCacheModel.specSchemaVersion =
			getSpecSchemaVersion();

		String specSchemaVersion =
			layoutContentVersionCacheModel.specSchemaVersion;

		if ((specSchemaVersion != null) && (specSchemaVersion.length() == 0)) {
			layoutContentVersionCacheModel.specSchemaVersion = null;
		}

		layoutContentVersionCacheModel.version = getVersion();

		layoutContentVersionCacheModel.status = getStatus();

		layoutContentVersionCacheModel.statusByUserId = getStatusByUserId();

		layoutContentVersionCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName =
			layoutContentVersionCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			layoutContentVersionCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			layoutContentVersionCacheModel.statusDate = statusDate.getTime();
		}
		else {
			layoutContentVersionCacheModel.statusDate = Long.MIN_VALUE;
		}

		return layoutContentVersionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LayoutContentVersion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LayoutContentVersion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LayoutContentVersion, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(LayoutContentVersion)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LayoutContentVersion>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					LayoutContentVersion.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private String _externalReferenceCode;
	private long _layoutContentVersionId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _data;
	private String _dataHash;
	private String _name;
	private String _nameCurrentLanguageId;
	private long _plid;
	private String _specSchemaVersion;
	private int _version;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<LayoutContentVersion, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LayoutContentVersion)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"externalReferenceCode", _externalReferenceCode);
		_columnOriginalValues.put(
			"layoutContentVersionId", _layoutContentVersionId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("data_", _data);
		_columnOriginalValues.put("dataHash", _dataHash);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("plid", _plid);
		_columnOriginalValues.put("specSchemaVersion", _specSchemaVersion);
		_columnOriginalValues.put("version", _version);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("data_", "data");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("externalReferenceCode", 2L);

		columnBitmasks.put("layoutContentVersionId", 4L);

		columnBitmasks.put("groupId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("userId", 32L);

		columnBitmasks.put("userName", 64L);

		columnBitmasks.put("createDate", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		columnBitmasks.put("data_", 512L);

		columnBitmasks.put("dataHash", 1024L);

		columnBitmasks.put("name", 2048L);

		columnBitmasks.put("plid", 4096L);

		columnBitmasks.put("specSchemaVersion", 8192L);

		columnBitmasks.put("version", 16384L);

		columnBitmasks.put("status", 32768L);

		columnBitmasks.put("statusByUserId", 65536L);

		columnBitmasks.put("statusByUserName", 131072L);

		columnBitmasks.put("statusDate", 262144L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LayoutContentVersion _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:753460274