modified.files.includes[relevant][core-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-*][relevant][core-java-rule]=\
    apps/**/src/testIntegration/**/*Test.java,\
    core/**/src/testIntegration/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][core-java-rule]=\
    apps/accessibility/**/*Test.java,\
    core/**/*Test.java

relevant.rule.names=core-java-rule

test.batch.names[relevant][core-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
    (environment.acceptance == true) AND \
    (\
        (app.server.types == null) OR \
        (app.server.types ~ "tomcat")\
    ) AND \
    (\
        (database.types == null) OR \
        (database.types ~ "mysql")\
    ) AND \
    (\
        (operating.system.types == null) OR \
        (operating.system.types ~ "centos")\
    )

testray.main.component.name=Portal Services