modified.files.includes[relevant][portal-scheduler-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][portal-scheduler-java-rule]=\
    apps/portal-scheduler/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][portal-scheduler-java-rule]=\
    apps/portal-scheduler/**/*Test.java

relevant.rule.names=portal-scheduler-java-rule

test.batch.names[relevant][portal-scheduler-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
    (\
        (portal.acceptance == true) AND \
        (testray.main.component.name == "Staging")\
    ) OR \
    (\
        (license.required != "true") AND \
        (testray.main.component.name == "Clustering")\
    ) OR \
    (testray.main.component.name == "Scheduler")

testray.main.component.name=Scheduler