dependencies {
	testIntegrationImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testIntegrationImplementation project(":apps:document-library:document-library-api")
	testIntegrationImplementation project(":apps:fragment:fragment-api")
	testIntegrationImplementation project(":apps:layout:layout-test-util")
	testIntegrationImplementation project(":apps:segments:segments-api")
	testIntegrationImplementation project(":apps:site:site-api")
	testIntegrationImplementation project(":apps:site:site-staticexport-api")
	testIntegrationImplementation project(":test:arquillian-extension-junit-bridge")
}