/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.portal.tools.service.builder.test.model.DynamicQueryEntry;
import com.liferay.portal.tools.service.builder.test.service.DynamicQueryEntryLocalServiceUtil;

/**
 * The extended model base implementation for the DynamicQueryEntry service. Represents a row in the &quot;DynamicQueryEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DynamicQueryEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DynamicQueryEntryImpl
 * @see DynamicQueryEntry
 * @generated
 */
public abstract class DynamicQueryEntryBaseImpl
	extends DynamicQueryEntryModelImpl implements DynamicQueryEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dynamic query entry model instance should use the <code>DynamicQueryEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			DynamicQueryEntryLocalServiceUtil.addDynamicQueryEntry(this);
		}
		else {
			DynamicQueryEntryLocalServiceUtil.updateDynamicQueryEntry(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-345679942