dependencies {
	testIntegrationImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testIntegrationImplementation group: "com.sun.mail", name: "jakarta.mail", version: "1.6.8"
	testIntegrationImplementation group: "javax.portlet", name: "portlet-api", version: "3.0.1"
	testIntegrationImplementation group: "org.apache.felix", name: "org.apache.felix.http.servlet-api", version: "1.1.2"
	testIntegrationImplementation project(":apps:asset:asset-display-page-api")
	testIntegrationImplementation project(":apps:dynamic-data-mapping:dynamic-data-mapping-api")
	testIntegrationImplementation project(":apps:info:info-api")
	testIntegrationImplementation project(":apps:journal:journal-api")
	testIntegrationImplementation project(":apps:journal:journal-test-util")
	testIntegrationImplementation project(":apps:layout:layout-page-template-api")
	testIntegrationImplementation project(":apps:layout:layout-test-util")
	testIntegrationImplementation project(":apps:portal-configuration:portal-configuration-test-util")
	testIntegrationImplementation project(":apps:static:portal-osgi-web:portal-osgi-web-portlet-container-test-util")
	testIntegrationImplementation project(":test:arquillian-extension-junit-bridge")
}