defaults:
    run:
        shell: bash
jobs:
    publish:
        env:
            GITHUB_TOKEN: ${{github.token}}
            IS_PR: ${{inputs.pr_number != ''}}
        permissions:
            contents: write
            id-token: write
            packages: write
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
                    filter: blob:none
                    show-progress: false
            -   if: ${{env.IS_PR == 'true'}}
                name: Modify version for pull request
                run: |
                    CHART_VERSION=$(cat ./Chart.yaml | yq .version)

                    SHORT_SHA=$(git rev-parse --short HEAD)

                    NEW_VERSION="${CHART_VERSION}-pr-${{inputs.pr_number}}-g${SHORT_SHA}"

                    echo "Modifying chart version from ${CHART_VERSION} to ${NEW_VERSION}."

                    yq -i ".version = \"${NEW_VERSION}\"" Chart.yaml
                working-directory: ${{inputs.working_directory}}
            -   id: verify_version
                name: Verify Helm chart version
                run: |
                    set -o errexit

                    CHART_VERSION=$(cat ./Chart.yaml | yq .version)

                    if [[ "${{env.IS_PR}}" == "true" ]]
                    then
                        REGISTRY="ghcr.io/${{github.repository_owner}}/charts-pr/${{inputs.pr_number}}"
                    else
                        REGISTRY="${{inputs.registry}}"
                    fi

                    echo "Verifying Helm chart version ${CHART_VERSION} in ${REGISTRY}."

                    if [[ "${{env.IS_PR}}" == "true" ]]
                    then
                        echo "Overwriting version ${CHART_VERSION} in GHCR if it exists."

                        echo "CHART_VERSION=${CHART_VERSION}" >> ${GITHUB_ENV}

                        echo "registry=${REGISTRY}" >> ${GITHUB_OUTPUT}

                        echo "should_publish=true" >> ${GITHUB_OUTPUT}
                    elif ! helm show readme "oci://${REGISTRY}/${{inputs.chart_name}}:${CHART_VERSION}" >/dev/null 2>&1
                    then
                        echo "Verified Helm Chart version ${CHART_VERSION}."

                        echo "CHART_VERSION=${CHART_VERSION}" >> ${GITHUB_ENV}

                        echo "registry=${REGISTRY}" >> ${GITHUB_OUTPUT}

                        echo "should_publish=true" >> ${GITHUB_OUTPUT}
                    else
                        echo "Chart version ${CHART_VERSION} already exists."
                    fi
                working-directory: ${{inputs.working_directory}}
            -   id: auth
                if: ${{env.IS_PR == 'false' && steps.verify_version.outputs.should_publish == 'true'}}
                name: Authenticate to Google Cloud
                uses: google-github-actions/auth@v2
                with:
                    service_account: ${{secrets.GCP_SA}}
                    token_format: access_token
                    workload_identity_provider: ${{secrets.GCP_WORKLOAD_IDENTITY_PROVIDER}}
            -   if: ${{env.IS_PR == 'false' && steps.verify_version.outputs.should_publish == 'true'}}
                name: Log in to GAR
                run: |
                    echo "${{steps.auth.outputs.access_token}}" \
                        | helm registry login "${{inputs.registry}}" \
                            --password-stdin \
                            --username oauth2accesstoken
            -   if: ${{env.IS_PR == 'true' && steps.verify_version.outputs.should_publish == 'true'}}
                name: Log in to GHCR
                run: |
                    echo "${{github.token}}" \
                        | helm registry login ghcr.io \
                            --password-stdin \
                            --username "${{github.actor}}"
            -   if: ${{steps.verify_version.outputs.should_publish == 'true'}}
                name: Package Helm chart
                run: |
                    set -o errexit

                    DIST_DIR="${{runner.temp}}/${{inputs.chart_name}}/dist"

                    rm --force --recursive "${DIST_DIR}"

                    mkdir --parents "${DIST_DIR}"

                    helm dependency update

                    helm package . \
                        --destination "${DIST_DIR}" \
                        --version "${CHART_VERSION}"
                working-directory: ${{inputs.working_directory}}
            -   if: ${{steps.verify_version.outputs.should_publish == 'true'}}
                name: Publish Helm chart
                run: |
                    set -o errexit

                    DIST_DIR="${{runner.temp}}/${{inputs.chart_name}}/dist"

                    for file_name in "${DIST_DIR}"/*.tgz
                    do
                        echo "Pushing ${file_name} to oci://${{steps.verify_version.outputs.registry}}."

                        helm push "${file_name}" "oci://${{steps.verify_version.outputs.registry}}"
                    done
                working-directory: ${{inputs.working_directory}}
on:
    workflow_call:
        inputs:
            chart_name:
                required: true
                type: string
            pr_number:
                default: ""
                required: false
                type: string
            registry:
                required: true
                type: string
            working_directory:
                required: true
                type: string
permissions:
    contents: write
    id-token: write
    packages: write