modified.files.includes[relevant][address-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][address-java-rule]=\
    apps/address/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][address-java-rule]=\
    apps/address/**/*Test.java

relevant.rule.names=address-java-rule

test.batch.names[relevant][address-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
    (portal.acceptance == true) AND \
    (\
        (testray.component.names ~ "Address") OR \
        (testray.main.component.name ~ "Address")\
    )

testray.main.component.name=Address