modified.files.includes[relevant][wiki-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][wiki-java-rule]=\
    apps/wiki/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][wiki-java-rule]=\
    apps/wiki/**/*Test.java

relevant.rule.names=wiki-java-rule

test.batch.names[relevant][wiki-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
    (portal.acceptance == true) AND \
    (\
        (testray.component.names ~ "Wiki") OR \
        (testray.main.component.name ~ "Wiki")\
    )

testray.main.component.name=Wiki